### ISSUE TITLE
Poor Performance of Kotlin/JS

### ISSUE THREAD

**Issue by baconz** [apollographql/apollo-kotlin#4728] opened 2023-03-03 07:41 UTC
### Version

3.7.4

### Summary

Comparing performance of Kotlin/JS running Apollo and the JS client (`@apollo/client`), the time to build a `Call` is ~7x worse and the time to parse responses is ~10x worse.

I have created a small project that demonstrates the performance discrepancy here: https://github.com/baconz/apollo-kotlin-js-performance. To use it, start up the web page (`./gradlew jsBrowserRun`), and capture a profile. You can see the time spent in Kotlin/JS is significantly more than the time spent in `@apollo/client`.

Barring major changes to the runtime, I'm wondering if there is a way that `apollo-kotlin` could simply "shell out" to `@apollo/client` to run the query, and then ~use reflection~ (right, we have no reflection because we have no JVM) use our knowledge of the schema (???) to grab the appropriate fields out of the resulting JS object. I can try to put up a POC tomorrow.

**Comment by martinbonnin** [comment] 2023-03-03 09:27
Many thanks for filing this and the reproducer project 🙏 We'll dig into performance issues. The `Call` in particular seems worrysome since there shouldn't be that many things happening there.

About the suggestion of wrapping `@apollo/client`, I think that's a very reasonable approach to do in your project if you want speed and can work without the typesafe models (or map them, but you might have to pay the parsing time fee here?). But it's unlikely to make it to apollo-kotlin because the surface API is just too big. Stuff like the normalized cache, typesafe models, different codegen options, etc... will be close to impossible to map to `@apollo/client`

**Comment by martinbonnin** [comment] 2023-03-03 10:35
Did a bit of browsing of [#javascript](https://slack-chats.kotlinlang.org/t/8427960/hi-guys-is-kotlin-js-stable-at-the-moment-i-last-checked-a-f#463b7f1e-e7c5-4726-bb4c-2319c686a325) in KotlinLang's slack and looks like type checking is particularly slow: https://youtrack.jetbrains.com/issue/KT-24784. Might be something to investigate.

**Comment by baconz** [comment] 2023-03-03 17:32
Yeah, I saw that ticket -- it looks a bit old. To me it seems like the issue is a combination of the fact that every primitive is wrapped, and that the JSON parser is extremely slow.

I was thinking more about calling into the JS client. Would it be possible for `apollo-kotlin` to conditionally generate external `Data` interfaces? It seems like at parse time it would have everything it needs to be able to do that. This would allow us to take the output of the JS client and munge it into the "real" `Data` class from Kotlin code.

**Comment by martinbonnin** [comment] 2023-03-03 17:38
Not super familiar with external interfaces. I'll dig. First thing that comes to mind is: can regular Kotlin classes implement external interfaces? We'd still need the classes for other targets than JS.

```kotlin
class Query {
  external interface Data {
    val field: String
  }

  // Does that work?
  class DataImpl(override val field: String): Data 
}
```

**Comment by martinbonnin** [comment] 2023-03-03 17:44
IntelliJ doesn't like too much when I put `external` in common code

![Screenshot 2023-03-03 at 18 39 54](https://user-images.githubusercontent.com/3974977/222790094-250cc909-70c6-47b7-9b47-e99410f8ad5c.png)

So looks like we can't really make them the share the same type underlying type. You could always `JSON.stringify` your object and then parse it to a model (basically [skipping the runtime](https://www.apollographql.com/docs/kotlin/advanced/no-runtime/)) but you'd still pay the serialization price.

**Comment by baconz** [comment] 2023-03-03 18:10
Ah, indeed. What about having a separate js-only task that generates js-only interfaces into the js source set?

**Comment by martinbonnin** [comment] 2023-03-03 18:12
>  What about having a separate js-only task that generates js-only interfaces into the js source set?

We could certainly do that (maybe it's even a completely separate Gradle plugin?) but you wouldn't be able to use those js-only interfaces in `commonMain`, would that be ok? Or you'd have to map to the `commonMain` data manually?

**Comment by baconz** [comment] 2023-03-03 18:31
I think it would be ok -- I think any form of this solution would require us to implement js-specific repositories that get injected into the common code.

**Comment by martinbonnin** [comment] 2023-03-03 18:43
One thing to note is that if we go down this road is that external interfaces would have to be `responseBased` by definition (see [documentation](https://www.apollographql.com/docs/kotlin/advanced/response-based-codegen/) about different codegeneration modes and [this blog post](https://www.apollographql.com/docs/kotlin/advanced/response-based-codegen/) about some background). 

By default the Kotlin models are based on the operations `operationBased`. 

This is not an issue if you don't use any fragments but as soon as you start having fragments and polymorphism, `operationBased` will not match `responseBased` so you'll certainly have to switch to `responseBased` for easier mappers. And that comes with tradeoffs. Not saying this is not doable but your simple query might turn up quite complicated once you start adding fragments, `@include`/`@skip` directive and other things.

**Comment by baconz** [comment] 2023-03-03 18:52
That makes sense. We are currently using `operationBased`, but honestly I wasn't aware of the distinction. Having fragments represented as interfaces seems really nice, since it allows us to avoid hardcoded `__typename` all over the place. At any rate, definitely doesn't seem like a dealbreaker for this.

**Comment by martinbonnin** [comment] 2023-03-03 19:23
Now that I think about it, I'm not even sure how external interfaces would handle polymorphism. 

simple example:
```graphql
query GetAnimal {
  animal {
    __typename
    ... on Cat {
      meox
    }
    ... on Lion {
      roar
    }
  }
}
```

Kotlin: 

```kotlin
external interface Animal {
  val __typename: String
}

external interface Lion: Animal { // not even sure it is possible to extend external interfaces but assuming it is
  override val __typename: String
  val roar: String
}

// Usage
if (data.animal is Lion) { // pretty sure that's not possible
  println(data.animal.roar)
}
```

The [Kotlin doc](https://kotlinlang.org/docs/js-interop.html#casts) is pretty explicit that external interfaces are not retained at runtime (which makes sense):

```
They can't be used on the right-hand side of is checks
```

That pretty much forbids any fragment usage from these JS land external interfaces....

**Comment by baconz** [comment] 2023-03-03 20:47
I think you'd handle this with some type assertions, which doesn't seem too bad:

```
when (data.__typename) {
   "Lion" -> println((data.animal as Lion).roar)
}
```

**Comment by martinbonnin** [comment] 2023-03-03 21:46
Fair enough 👍 . I opened https://github.com/apollographql/apollo-kotlin/issues/4732 to keep track of progress there and keep this issue for Kotlin/JS performance

**Comment by baconz** [comment] 2023-03-03 21:56
Makes sense to me. I think we could use my little repro project to test out the external interfaces.

I think this ticket might be relevant here https://github.com/Kotlin/kotlinx.serialization/issues/907

**Comment by baconz** [comment] 2023-03-06 07:18
I created this ticket as a one possible direction: https://youtrack.jetbrains.com/issue/KT-57128/Kotlin-JS-Can-Long-use-BigInt-internally-and-polyfill-if-it-is-unavailable

Unfortunately, a lot of our devices are running older Chromes and won't support BigInt, but it is at least something to investigate.

**Comment by martinbonnin** [comment] 2023-06-21 09:07
Hi @baconz 👋 With all the work you've done on `@JsExport` and [JS interop in general](https://www.apollographql.com/docs/kotlin/v4/advanced/js-interop) (thanks again!) I'm going to close this issue and let the community open new more specific ones if needed. JS performance might not be on par with JVM at the moment but `@JsExport` and `DynamicJsJsonParser` should offer reasonable mitigations.

**Closed by martinbonnin** 2023-06-21 09:07 UTC
Labels: :bug: Type: Bug
