### ISSUE TITLE
Cannot see payload and response when inspect the app

### ISSUE THREAD

**Issue by muslimmuda15** [apollographql/apollo-kotlin#5509] opened 2024-01-08 09:04 UTC
### Question

I try to debug my app using `profiler`. I can see the diagram, but can't see the information
![image](https://github.com/apollographql/apollo-kotlin/assets/26782958/159d632b-973a-4256-9fd4-7b8e01b56970)

This is my version
```
Android Studio Giraffe | 2022.3.1 Patch 4
Build #AI-223.8836.35.2231.11090377, built on November 14, 2023
Runtime version: 17.0.6+0-b2043.56-10027231 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1522M
Cores: 4
Registry:
    undo.documentUndoLimit=1000
    undo.globalUndoLimit=1000
    external.system.auto.import.disabled=true
    debugger.watches.in.variables=false
    ide.text.editor.with.preview.show.floating.toolbar=false

Non-Bundled Plugins:
    com.intellij.marketplace (223.8836.56)
    Dart (223.8977)
    com.intellij.lang.jsgraphql (4.0.1-222)
    org.jetbrains.action-tracker (0.3.3)
    com.thoughtworks.gauge (223.7571.182)
    io.flutter (76.3.2)
```

This is my gradle configuration
```
plugins {
    id 'com.android.application' version '8.1.2' apply false
    id 'com.google.devtools.ksp' version '1.9.10-1.0.13' apply false
    id 'com.apollographql.apollo3' version '3.8.2' apply false
    id 'com.google.dagger.hilt.android' version '2.48.1' apply false
    // ...
}

plugins {
    id 'com.android.application'
    id 'com.apollographql.apollo3'
    id 'kotlin-kapt'
    // ...
}

android {
    // ....
    namespace "sg.com.appety.waiterapp"
    compileSdk 34
    buildFeatures {
        viewBinding true
    }
    defaultConfig {
        applicationId = "sg.com.myapp"
        minSdk 26
        targetSdk 34
        // ...
    }
    compileOptions {
        sourceCompatibility 17
        targetCompatibility 17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
}

apollo {
    service("myapp") {
        packageName.set("sg.com.myapp")
        introspection {
            endpointUrl.set("https://localhost:3000/")
            schemaFile.set(file("src/main/graphql/sg/com/myapp/schema.graphqls"))
        }
        customTypeMapping = [
                "Date"    : "kotlin.String",
                "DateTime": "kotlin.String",
                "Time"    : "kotlin.String",
                "BigInt"  : "kotlin.Long",
                "Double"  : "kotlin.Double"
        ]
    }
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib:1.9.0"
    implementation 'androidx.core:core-ktx:1.9.0'
    implementation 'com.apollographql.apollo3:apollo-runtime:3.8.2'
    implementation 'com.apollographql.apollo3:apollo-api:3.8.2'
    // ...
}

kapt {
    correctErrorTypes true
}
```

If you need more information, please let me know.
Thanks

**Comment by BoD** [comment] 2024-01-08 10:20
Hi! I've just tried on a demo app, and this worked for me - albeit I'm on the latest AS stable (Hedgehog | 2023.1.1 Patch 1). Are you trying on the debug version of your app?

**Comment by martinbonnin** [comment] 2024-01-22 13:01
@muslimmuda15 this looks like and Android Studio issue. Without a reproducer, there's little we can do. Closing for now, please let us know if you want us to reopen.

**Closed by martinbonnin** 2024-01-22 13:01 UTC
Labels: :question: Type: Question, :hourglass:  Waiting for info

**Comment by muslimmuda15** [comment] 2024-03-19 06:07
After update into iguana, the problem was solved.
Thanks
