### ISSUE TITLE
After updating to 3.1 on Android we're seeing a new spike in SocketExceptions

### ISSUE THREAD

**Issue by jeffreydecker** [apollographql/apollo-kotlin#3903] opened 2022-03-02 05:32 UTC
**Summary**
After migrating to 3.1 we're starting to see a spike in SocketExceptions from our bug reporting that wasn't present pre-migration.

**Version**
Apollo 3.1.0 for Android

**Description**
Unfortunately I don't have more information at this time for repro steps but we do have 2 prolific stack traces available that I can share. I'm just beginning to investigate this issue and can share more details as I have them. It's possible that this isn't related to the migration but that's the best guess right now. My goal for posting this here early on is to see if anyone recognizes what the issue could be. It could certainly be an issue with the updated integration so any suggestions to try are very welcome as I set out on my investigation. I do know that as a part of migrating to 3.1 this Okio and OkHttp updated too so I'll also be looking there as well.

Stack Trace 1

```
Fatal Exception: java.net.SocketException: Socket is closed
       at com.android.org.conscrypt.AbstractConscryptSocket.checkOpen(AbstractConscryptSocket.java:581)
       at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:532)
       at okio.InputStreamSource.read(JvmOkio.kt:94)
       at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:125)
       at okio.internal._RealBufferedSourceKt.commonRead(_RealBufferedSourceKt.java:39)
       at okio.RealBufferedSource.read(RealBufferedSource.kt:65)
       at okio.RealBufferedSource.read(RealBufferedSource.kt:65)
       at okio.RealBufferedSource.read(RealBufferedSource.kt:65)
       at okhttp3.internal.http1.Http1ExchangeCodec$AbstractSource.read(Http1ExchangeCodec.kt:331)
       at okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.read(Http1ExchangeCodec.kt:412)
       at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:276)
       at okio.internal._RealBufferedSourceKt.commonRead(_RealBufferedSourceKt.java:39)
       at okio.RealBufferedSource.read(RealBufferedSource.kt:65)
       at okio.RealBufferedSource.read(RealBufferedSource.kt:65)
       at okio.RealBufferedSource.read(RealBufferedSource.kt:65)
       at okio.internal._RealBufferedSourceKt.commonRequest(_RealBufferedSourceKt.java:60)
       at okio.RealBufferedSource.request(RealBufferedSource.kt:68)
       at okio.RealBufferedSource.request(RealBufferedSource.kt:68)
       at okio.internal._RealBufferedSourceKt.commonRequire(_RealBufferedSourceKt.java:53)
       at okio.RealBufferedSource.require(RealBufferedSource.kt:67)
       at okio.GzipSource.consumeHeader(GzipSource.kt:104)
       at okio.GzipSource.read(GzipSource.kt:62)
       at okio.internal._RealBufferedSourceKt.commonRequest(_RealBufferedSourceKt.java:60)
       at okio.RealBufferedSource.request(RealBufferedSource.kt:68)
       at okio.RealBufferedSource.request(RealBufferedSource.kt:68)
       at com.apollographql.apollo3.api.json.BufferedSourceJsonReader.nextNonWhitespace(BufferedSourceJsonReader.kt:809)
       at com.apollographql.apollo3.api.json.BufferedSourceJsonReader.doPeek(BufferedSourceJsonReader.kt:242)
       at com.apollographql.apollo3.api.json.BufferedSourceJsonReader.peek(BufferedSourceJsonReader.kt:130)
       at com.apollographql.apollo3.api.json.-JsonReaders.readAny(JsonReaders.kt:26)
       at com.apollographql.apollo3.api.Adapters$AnyAdapter$1.fromJson(Adapters.kt:171)
       at com.apollographql.apollo3.api.Adapters$AnyAdapter$1.fromJson(Adapters.kt:180)
       at com.apollographql.apollo3.network.http.BatchingHttpInterceptor.executePendingRequests(BatchingHttpInterceptor.kt:198)
       at com.apollographql.apollo3.network.http.BatchingHttpInterceptor.access$getBatchIntervalMillis$p(BatchingHttpInterceptor.kt:65)
       at com.apollographql.apollo3.network.http.BatchingHttpInterceptor$1.invokeSuspend(BatchingHttpInterceptor.kt:84)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:929)
```

Stack Trace 2

```
Fatal Exception: java.net.SocketException: Socket is closed
       at org.conscrypt.AbstractConscryptSocket.checkOpen(AbstractConscryptSocket.java:574)
       at org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:186)
       at org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:770)
       at okio.InputStreamSource.read(JvmOkio.kt:94)
       at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:125)
       at okio.internal._RealBufferedSourceKt.commonRead(_RealBufferedSourceKt.java:39)
       at okio.RealBufferedSource.read(RealBufferedSource.kt:65)
       at okio.RealBufferedSource.read(RealBufferedSource.kt:65)
       at okio.RealBufferedSource.read(RealBufferedSource.kt:65)
       at okhttp3.internal.http1.Http1ExchangeCodec$AbstractSource.read(Http1ExchangeCodec.kt:331)
       at okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.read(Http1ExchangeCodec.kt:412)
       at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:276)
       at okio.internal._RealBufferedSourceKt.commonRead(_RealBufferedSourceKt.java:39)
       at okio.RealBufferedSource.read(RealBufferedSource.kt:65)
       at okio.RealBufferedSource.read(RealBufferedSource.kt:65)
       at okio.RealBufferedSource.read(RealBufferedSource.kt:65)
       at okio.internal._RealBufferedSourceKt.commonExhausted(_RealBufferedSourceKt.java:49)
       at okio.RealBufferedSource.exhausted(RealBufferedSource.kt:66)
       at okio.RealBufferedSource.exhausted(RealBufferedSource.kt:66)
       at okio.InflaterSource.refill(InflaterSource.kt:112)
       at okio.InflaterSource.readOrInflate(InflaterSource.kt:76)
       at okio.InflaterSource.read(InflaterSource.kt:49)
       at okio.GzipSource.read(GzipSource.kt:69)
       at okio.internal._RealBufferedSourceKt.commonIndexOfElement(_RealBufferedSourceKt.java:355)
       at okio.RealBufferedSource.indexOfElement(RealBufferedSource.kt:126)
       at okio.RealBufferedSource.indexOfElement(RealBufferedSource.kt:126)
       at okio.RealBufferedSource.indexOfElement(RealBufferedSource.kt:124)
       at com.apollographql.apollo3.api.json.BufferedSourceJsonReader.nextQuotedValue(BufferedSourceJsonReader.kt:604)
       at com.apollographql.apollo3.api.json.BufferedSourceJsonReader.nextString(BufferedSourceJsonReader.kt:465)
       at com.apollographql.apollo3.api.json.-JsonReaders.readAny(JsonReaders.kt:30)
       at com.apollographql.apollo3.api.json.-JsonReaders.readAny(JsonReaders.kt:35)
       at com.apollographql.apollo3.api.json.-JsonReaders.readAny(JsonReaders.kt:35)
       at com.apollographql.apollo3.api.json.-JsonReaders.readAny(JsonReaders.kt:35)
       at com.apollographql.apollo3.api.json.-JsonReaders.readAny(JsonReaders.kt:44)
       at com.apollographql.apollo3.api.json.-JsonReaders.readAny(JsonReaders.kt:35)
       at com.apollographql.apollo3.api.json.-JsonReaders.readAny(JsonReaders.kt:35)
       at com.apollographql.apollo3.api.json.-JsonReaders.readAny(JsonReaders.kt:35)
       at com.apollographql.apollo3.api.json.-JsonReaders.readAny(JsonReaders.kt:44)
       at com.apollographql.apollo3.api.json.-JsonReaders.readAny(JsonReaders.kt:35)
       at com.apollographql.apollo3.api.json.-JsonReaders.readAny(JsonReaders.kt:35)
       at com.apollographql.apollo3.api.json.-JsonReaders.readAny(JsonReaders.kt:35)
       at com.apollographql.apollo3.api.json.-JsonReaders.readAny(JsonReaders.kt:44)
       at com.apollographql.apollo3.api.Adapters$AnyAdapter$1.fromJson(Adapters.kt:171)
       at com.apollographql.apollo3.api.Adapters$AnyAdapter$1.fromJson(Adapters.kt:180)
       at com.apollographql.apollo3.network.http.BatchingHttpInterceptor.executePendingRequests(BatchingHttpInterceptor.kt:198)
       at com.apollographql.apollo3.network.http.BatchingHttpInterceptor.access$getBatchIntervalMillis$p(BatchingHttpInterceptor.kt:65)
       at com.apollographql.apollo3.network.http.BatchingHttpInterceptor$1.invokeSuspend(BatchingHttpInterceptor.kt:84)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
```

Thanks

**Comment by martinbonnin** [comment] 2022-03-03 00:40
Gotcha 👍 . I was only looking at the 3.0 -> 3.1 changelog. The 2.5.9 -> 3.0 changelog is a lot bigger and is wayyy more prone to contain the culprit change. It could be headers but I don't buy it too much TBH.  

A few more questions:

* I'm assuming you can only see this in bug reporting, right? There's no way to reproduce this 100%? 
* If you have some error reporting on your backend, can you see anything wrong there?
* Could it be some lifecycle issue maybe? Because 3.0 is using coroutines, the lifecycle handling has somewhat changed and if the network is lost while somewhere while a batch is ongoing it would trigger such exceptions. Sounds like a stretch but it might be worth double checking?

**Comment by jeffreydecker** [comment] 2022-03-03 00:50
Yeah unfortunately I haven't been able to repro at all. We're just seeing it in reporting at this point in time. We do have some info on user actions leading up to the error but haven't been lucky enough to actually trigger the issue following those unfortunately. 

Good call out on the backend though. I can check with the team there to see if there is anything that might help. As for the lifecycle. It could be related although we did update to using coroutines in 2.5.9 to make sure they alone wouldn't be a problem. It could certainly still be related. 

We'll be rolling out some different variants that have the current implementation, batching disabled, and batching going through a copy of the interceptor from 3.0 just to see which if any of those options sees the issue go away. It may be none of these things as well. Either way I appreciate the help. Will report back once we have some findings.

**Comment by jeffreydecker** [comment] 2022-03-04 08:59
So far it looks like this is related to batching. After adding the older interceptor and looking at the code again I think the problem is related to how exceptions are being caught. The catch is only catching `ApolloException`s so the `SocketException` isn't being handled. I'm fairly new to coroutines but it appears that this uncaught exception is never propagated up for us to be handled where we execute the request. I think this has to do with scope but I'm unsure. There may be a way to capture it that I'm unaware of but our catch there doesn't get hit. Ee're also using `asFlow` and then converting that to an `Observable` to work with RX using kotlinx.coroutines so I may be missing some exception handling along the way. 

That said, if I manually throw a `SocketException` from the batching code I'm able to somewhat repro the issue in that I see a crash with a similar but abbreviated stack trace. By updating the line [here](https://github.com/apollographql/apollo-kotlin/blob/41dabec8455b6d30b620e0db6354b91602733fce/apollo-runtime/src/commonMain/kotlin/com/apollographql/apollo3/network/http/BatchingHttpInterceptor.kt#L211) to catch `Exception` instead of `ApolloException` specifically and either wrapping that in an `ApolloException` when it isn't already one or modify the code to throw generic exceptions I do receive the error where we can handle it. I think this would probably be a good change to make so the top level catches get called with the error.

**Comment by martinbonnin** [comment] 2022-03-04 09:22
Yikes, good catch ! Exception handling is hard 😓 ... 

The request from [DefaultHttpEngine](https://github.com/apollographql/apollo-kotlin/blob/22c37ba29d506c0365b04f80563800223f318ad4/apollo-runtime/src/jvmMain/kotlin/com/apollographql/apollo3/network/http/OkHttpEngine.kt#L83) throws `ApolloException` but when reading the body later on, it doesn't wrap indeed :/. That'd explain why it's harder to reproduce as closing the connection during a request happens less frequently than not being able to connect or another HTTP error.

Do you want to open a pull request to make the change?

**Comment by jeffreydecker** [comment] 2022-03-04 20:00
Yeah no worries. Exception handling is definitely hard. We're running the experiment with the fix over the weekend just to make sure it all looks good but I can definitely put up a PR for the fix. Will work on getting that in soon.

**Closed** 2022-03-09 13:44 UTC
Labels: :beetle: Type: Bug
