### ISSUE TITLE
NullPointerException for Request with single-quote character

### ISSUE THREAD

**Issue by darvelo** [apollographql/apollo-kotlin#5233] opened 2023-09-12 17:47 UTC
### Version

3.8.2

### Summary

I believe I'm seeing the same behavior as #4566, where instead of space chars, a single-quote smart quote char `’` in a query parameter is causing Apollo-Kotlin to throw a NullPointerException when running `.execute()` on the query, via the iOS platform calling my underlying shared Kotlin HTTP layer code.

I can confirm that running the same query through a GraphQL GUI client calls the query successfully with the same input.

### Steps to reproduce the behavior

1. Write a query like:

```graphql
isUsernameAvailable(username: String!): Boolean!
```

2. On iOS, pass a `username` string that has a single-quote smart quote character at the end: `’`
3. Apollo-Kotlin throws a NullPointerException.

### Logs

```
(Your logs here)
```

**Comment by martinbonnin** [comment] 2023-09-12 18:45
Thanks for sending this. Tests [here](https://github.com/apollographql/apollo-kotlin/pull/5234). So far haven't been able to reproduce. A few questions to help pinpoint the issue:

* Can you share your whole query, the stacktrace  and a username that fails?
* Does it happen on Android or only iOS? 
* Are you using GET for your queries? I'm assuming APQs? Or Something else?

Thanks!

**Comment by darvelo** [comment] 2023-09-12 18:52
> Thanks for sending this. Tests [here](https://github.com/apollographql/apollo-kotlin/pull/5234). So far haven't been able to reproduce. A few questions to help pinpoint the issue:
> 
>     * Can you share your whole query, the stacktrace  and a username that fails?
> 
>     * Does it happen on Android or only iOS?
> 
>     * Are you using GET for your queries? I'm assuming APQs? Or Something else?
> 
> 
> Thanks!

Hi @martinbonnin , I'm in the process of upgrading to v4 to see if that helps, so I can't test further yet.

I see in your tests you've tested the literal single-quote char (on an English keyboard, `'`, equal to (U+00027), `&#39;` or `&apos;`), but have you tested the smart quote yet as mentioned above? The character is `’`, seems to be equal to (U+02019), `&#8217;` or `&rsquo;`.

**Comment by martinbonnin** [comment] 2023-09-12 20:14
> but have you tested the smart quote yet as mentioned above? The character is ’, seems to be equal to (U+02019), &#8217; or &rsquo;. 

Right on point 🎯 ! [I can reproduce now](https://github.com/apollographql/apollo-kotlin/pull/5234/commits/832d5354b4d4e8450f2b3f86d8449d2fd071ceac), thanks!

**Comment by martinbonnin** [comment] 2023-09-12 23:52
Fix is [there](https://github.com/apollographql/apollo-kotlin/pull/5234). Turns out if I'm reading https://developer.apple.com/documentation/foundation/nsurl right, the `NSURL` behaviour will change to percent-encode the required chars but this isn't out yet. In all cases, better urlencode correctly!

**Comment by darvelo** [comment] 2023-09-14 18:41
Amazing. As always, thanks for discovering and fixing the issue so quickly. Excellent work, too, referencing the RFC. 👏🏽

**Comment by BoD** [comment] 2023-09-15 10:23
Closing, for now the fix is available in the  [snapshots](https://github.com/apollographql/apollo-kotlin#snapshots), and will be in the next release of v4.

**Closed by BoD** 2023-09-15 10:23 UTC
Labels: :bug: Type: Bug
