### ISSUE TITLE
check_key_fields validation optimization for projects with heavily reused fragments

### ISSUE THREAD

**Issue by apramana** [apollographql/apollo-kotlin#3656] opened 2021-12-08 01:49 UTC
**Summary**
Codegen takes substantially longer in v3 compared to v2 in projects with heavily reused fragments due to `check_key_fields` validation.

**Version**
3.0.0-beta05

**Description**
Hello - I am in the process of migrating our project (which makes extensive use of nested and reused fragments) to Apollo 3, and noticed that the codegen task takes significantly longer for us than it does in v2. For comparison, codegen (excluding compilation) on our root module takes ~30s in v2 and ~3 min in v3.

To investigate, I cloned the Apollo compiler and found that most of the time was spent on the [checkKeyFields call on fragments](https://github.com/apollographql/apollo-android/blob/dev-3.x/apollo-compiler/src/main/kotlin/com/apollographql/apollo3/compiler/ApolloCompiler.kt#L122). Within [check_key_fields.kt](https://github.com/apollographql/apollo-android/blob/dev-3.x/apollo-ast/src/main/kotlin/com/apollographql/apollo3/ast/check_key_fields.kt), I added a println and noticed that identical paths are being checked more than once. Am I correct in understanding that `checkField` should only be called once per unique path value (and that selections remain stable)? If so, could a set of checked paths be maintained so that duplicate calls are avoided? This change substantially reduces the time this class takes to run (our root module codegen comes down to 40s with this optimization) but I'm unsure if it breaks the completeness.

**Comment by martinbonnin** [comment] 2021-12-08 09:33
Thanks for sending this! We [are monitoring the compile time](https://github.com/apollographql/apollo-android/blob/22c37ba29d506c0365b04f80563800223f318ad4/apollo-compiler/src/test/graphql/com/example/measurements#L1) but don't have any tests to detect such regressions at the moment. That's definitely something to add. 

> Am I correct in understanding that checkField should only be called once per unique path value 

In [CheckKeyFieldsScope.checkField](https://github.com/apollographql/apollo-android/blob/4a402d5ccc4e1a313dbc3918c75eb68239e537e6/apollo-ast/src/main/kotlin/com/apollographql/apollo3/ast/check_key_fields.kt#L17), `parentType` might be important too, not sure.

>  This change substantially reduces the time this class takes to run (our root module codegen comes down to 40s with this optimization)

That's impressive 👏 ! Want to open a pull request and we can go from there?

**Comment by BoD** [comment] 2021-12-13 12:51
Hi 👋

Trying to look at this, for now I couldn't reproduce a case where `checkKeyFields` takes significant time relatively to the rest of the compilation - albeit trying on various test cases, not a real project. Would you mind sharing how you singled out this method in your investigation? If possible it would be awesome if we could also have a look at your schema / operations (we understand if that's not possible). Thanks!

**Comment by martinbonnin** [comment] 2021-12-16 13:54
@apramana can you check with `3.0.0` and https://github.com/apollographql/apollo-kotlin/pull/3720 ? It has an optimization to disable this check early if not needed

**Comment by apramana** [comment] 2021-12-17 00:19
@martinbonnin Awesome thanks for the patch, the build speed is much better now. For reference, I tested compilation of Apollo 3.0 GA in a multi-module project using `compat` codegen (though it probably doesn’t matter which one is used since this bug is in AST generation.)

Also, I’ve posted [a PR](https://github.com/apollographql/apollo-kotlin/pull/3740) for optimizing fragment spreads. Please take a look and provide any feedback.

**Comment by martinbonnin** [comment] 2021-12-17 07:36
All the thanks goes to @BoD who did all the work there :-)

Thanks for the PR, we'll take a look quickly !

**Comment by apramana** [comment] 2022-01-29 18:44
@martinbonnin @BoD I noticed that Apollo React provides [the ability to disable normalization](https://www.apollographql.com/docs/react/caching/cache-configuration/#disabling-normalization) for specific types. Does apollo-kotlin support this? (And if so, can this be used to exclude types from validation?)

**Comment by martinbonnin** [comment] 2022-01-31 07:59
@apramana we don't have anything like this at the moment. Feel free to open a separate issue to track this.

**Comment by martinbonnin** [comment] 2022-03-25 12:37
I'm closing this one in favor of https://github.com/apollographql/apollo-kotlin/issues/3966. As of `3.1.0`, anyone not using `@fieldPolicy` or `@typePolicy` should never bump into this issue. 

In the future, we'll want to optimize that part of the codegen but before we optimise, we'll need a measure of what we're optimizing, which is what the above issue is about.

**Closed by martinbonnin** 2022-03-25 12:37 UTC
Labels: :beetle: Type: Bug
