### ISSUE TITLE
Migrate 2.xx to 3.0.3 about multiple services with mapScalar

### ISSUE THREAD

**Issue by annchar** [apollographql/apollo-kotlin#4176] opened 2022-06-08 10:08 UTC
**Question.**
I try to migrate apollo 2.xx to 3.0.3 but I have a problem when I import packages on DI file with mapScalar
For example, on build.gradle I set like this

```
apollo {
    useSchemaPackageNameForFragments.set(true)

    service("services1") {
        sourceFolder.set("com/services1")
        packageName.set("com.services1")
        mapScalar("DateTime", "java.util.Date")
        mapScalar("Date", "kotlin.String")
    }
    service("services2") {
        sourceFolder.set("com/services2")
        packageName.set("com.services2")
        mapScalar("DateTime", "java.util.Date")
        mapScalar("Date", "kotlin.String")
    }
}

```

DI.kt 
Service1
```
@Provides
@Singleton
@Named("service1")
fun provideServiceClient(
    @ApplicationContext context: Context,
    ...
): ApolloClient {

    val datetimeAdapter = object : Adapter<Date> {
        @SuppressLint("SimpleDateFormat")
        override fun fromJson(reader: JsonReader, customScalarAdapters: CustomScalarAdapters): Date {
            return try {
                val serverFormat = SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss'Z'")
                serverFormat.timeZone = TimeZone.getTimeZone("UTC")
                reader.nextString()?.let { serverFormat.parse(it) } ?: Date()
            } catch (e: ParseException) {
                Date()
            }
        }

        @SuppressLint("SimpleDateFormat")
        override fun toJson(writer: JsonWriter, customScalarAdapters: CustomScalarAdapters, value: Date) {
            writer.value(SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss'Z'").format(value))
        }
    }

    val dateAdapter = object : Adapter<String> {
        override fun fromJson(reader: JsonReader, customScalarAdapters: CustomScalarAdapters): String {
            return try {
                reader.nextString()?: ""
            } catch (e: ParseException) {
                ""
            }
        }

        override fun toJson(writer: JsonWriter, customScalarAdapters: CustomScalarAdapters, value: String) {
            writer.value(value)
        }
    }

    val instance = ApolloClient.Builder()
        .serverUrl(environment.serviceUrl)
        .okHttpClient(okHttpClient)
        .addCustomScalarAdapter(com.services1.type.Date.type, dateAdapter)
        .addCustomScalarAdapter(com.services1.type.DateTime.type, datetimeAdapter)
        .build()

    return instance!!
}
```

Service2 in the same DI.kt

```
    @Provides
    @Singleton
    @Named("service2")
    fun provideCmsClient(
        @ApplicationContext context: Context,
        ...
    ): ApolloClient {

        val datetimeAdapter = object : Adapter<Date> {
            @SuppressLint("SimpleDateFormat")
            override fun fromJson(reader: JsonReader, customScalarAdapters: CustomScalarAdapters): Date {
                return try {
                    val serverFormat = SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss'Z'")
                    serverFormat.timeZone = TimeZone.getTimeZone("UTC")
                    reader.nextString()?.let { serverFormat.parse(it) } ?: Date()

                } catch (e: ParseException) {
                    Date()
                }
            }

            @SuppressLint("SimpleDateFormat")
            override fun toJson(writer: JsonWriter, customScalarAdapters: CustomScalarAdapters, value: Date) {
                writer.value(SimpleDateFormat("MM-dd'T'HH:mm:ss'Z'").format(value))
            }
        }

        val instance = ApolloClient.Builder()
            .serverUrl(environment.cmsUrl)
            .okHttpClient(okHttpClient)
            .addCustomScalarAdapter(com.service2.type.DateTime.type, datetimeAdapter)
            .build()

        return instance!!
    }
```
I can't import DateTime.type and Date.type on DI.kt
I try to set gradle like this but is not success
```
apollo {
    useSchemaPackageNameForFragments.set(true)
    mapScalar("DateTime", "java.util.Date")
    mapScalar("Date", "kotlin.String")
    service("services1") {
        sourceFolder.set("com/services1")
        packageName.set("com.services1")
    }
    service("services2") {
        sourceFolder.set("com/services2")
        packageName.set("com.services2")
    }
}

```
**Does anyone know how to resolve it?**

**Comment by annchar** [comment] 2022-06-08 10:29
Thank you for your response! from your package I saw only `service1 [main] sources root folder` and `service2 [main] sources root folder ` don't have file on the package

**Comment by martinbonnin** [comment] 2022-06-08 10:44
Thanks for the details 🙏 . 

> service1 [main] sources root folder is empty

It looks like your `.graphql` files aren't found. By default, Apollo is looking for `.graphql` files in `src/main/graphql`. By setting `sourceFolder.set("com/services1")`, it will look in `src/main/graphql/com/services1`. Can you double check ?

**Comment by annchar** [comment] 2022-06-08 10:54
Yes, sure. After I checked,  the package I found many files mygraph.graphql and .schema.json. All files are the original before migration.

**Comment by martinbonnin** [comment] 2022-06-08 11:34
Hi 👋 . Is it working now? The code you shared is from `2.x` so looks like you're looking at older files? Any chance you might setup a small reproducer project somewhere? It'll help a ton to troubleshoot.

**Comment by annchar** [comment] 2022-06-08 11:36
Hi, I use
```
.addCustomScalarAdapter(CustomScalarType("Date","com.services1.type.CustomType.Date"), dateAdapter)
.addCustomScalarAdapter(CustomScalarType("DateTime", "com.services2.type.CustomType.DateTime"), datetimeAdapter)
```
Build output show the error
`Caused by: java.lang.IllegalStateException: Apollo: unknown custom scalar(s) in customScalarsMapping: Date
`
How to resolve it?

**Comment by annchar** [comment] 2022-06-08 11:40
Do you know how to ignore it or do you have any suggestions for me? I can't run on Android

**Comment by annchar** [comment] 2022-06-08 11:52
Many Thanks, I have another question. From v2 I used `getOrThrow()` like this

`apollo.query(GetDetailQuery(id)).execute().getOrThrow().detail`

How to use `getOrThrow()` on v3? I didn't see on the document.

**Comment by martinbonnin** [comment] 2022-06-08 12:11
1. you can use `dataAssertNoErrors` instead of `getOrThrow`, I'll add a deprecated migration helper to ease the transition.

2. We just made [a fix for this](https://github.com/apollographql/apollo-kotlin/pull/4154). You can either:
* Use the [SNAPSHOTS](https://github.com/apollographql/apollo-kotlin#snapshots)
* Or keep using `3.3.0` and use an alias for `Me`:
```graphql
query MyQuery {
  me: Me {
    name
    # ...
  }
}
```

**Comment by annchar** [comment] 2022-06-08 12:12
It's all clear! Thank you ka.

**Comment by martinbonnin** [comment] 2022-06-08 12:12
Sure thing, let me know how that goes!

**Comment by annchar-opn** [comment] 2022-06-09 09:14
Hi 👋, I try to migrate but I can't import the 2 packages
1. On ApolloClient `.addApplicationInterceptor()`
```
val instance = ApolloClient.Builder()
            .serverUrl(environment.cmsUrl)
            .okHttpClient(okHttpClient)
            .addApplicationInterceptor(...)
            .addCustomScalarAdapter(CustomScalarType("DateTime", "com.service1.type.DateTime.type"), datetimeAdapter)
            .build()  
```
2. On Service `.enqueue(null)` I didn't see on the migration document
`serviceClient.mutation(CreateMutation()).enqueue(null)`

**Comment by martinbonnin** [comment] 2022-06-09 09:20
1. For interceptors, you can use `addInterceptor()`. It's using a coroutines API now so you'll have to adapt your existing interceptor

2. There is no `enqueue` anymore because it's all using coroutines APIs. You can use `serviceClient.mutation(CreateMutation()).execute()` instead

**Comment by annchar-opn** [comment] 2022-06-09 09:30
> 1. For interceptors, you can use `addInterceptor()`. It's using a coroutines API now so you'll have to adapt your existing interceptor
> 2. There is no `enqueue` anymore because it's all using coroutines APIs. You can use `serviceClient.mutation(CreateMutation()).execute()` instead

Thanks for your fast response. let me try migration again

**Comment by annchar** [comment] 2022-06-09 09:31
> 1. For interceptors, you can use `addInterceptor()`. It's using a coroutines API now so you'll have to adapt your existing interceptor
> 2. There is no `enqueue` anymore because it's all using coroutines APIs. You can use `serviceClient.mutation(CreateMutation()).execute()` instead

Thanks for your fast response. let me try again

**Closed** 2022-06-10 11:00 UTC
Labels: :question: Type: Question
