### ISSUE TITLE
Marshal methods and multiple fragments using the same structure

### ISSUE THREAD

**Issue by tlevavasseur** [apollographql/apollo-kotlin#3672] opened 2021-12-09 15:58 UTC
Marshal methods have problems with multiple fragments using (partially) the same structure

Apollo 2.5.9

Combining fragments as a workaround of the lack of inheritance : 

```graphql
// just using partial media structure in Light object 
fragment ProductLightFragment on Product { 
    id, 
    name, 
    media { images } 
}

// using the rest of media structure on complete product
fragment ProductCompleteFragment on Product {
   ...ProductLightFragment,
   media { videos }
}
```

This is just a small example, my real Product structure is really big and I really want to use fragments combination.

No problem with this as a client, the parsing works and you can reach the images via the "light" fragment and videos via the "complete" fragment in return of the query. 

But using the marshal methods in my embedded mock server leads to a merge problem in the final json : 
```kotlin
    val writer = SimpleResponseWriter(ScalarTypeAdapters(customAdapters))
    data.marshaller().marshal(writer)
     val json = writer.toJson(null)
     response.setBody(json)
```
Only one of the partial media structure of the two fragments is serialized, here the light version (only the images are returned in the media node of the final json). Then the client fails to parse media for the "complete" fragment.

Probably one of those 2 situations : 
-  one marshaller overwrites the "media" node of the other
-  one marshaller cannot write in "media" node because the other already did it

**Comment by martinbonnin** [comment] 2021-12-09 16:06
Hi 👋 !

Thanks for sending this. This problem happens when using [merged fields](https://spec.graphql.org/draft/#sec-Field-Selection-Merging). This is unfortunately a limitation in the 2.x version and pretty hard to fix without breaking the API.

The good news is that significant work was made in 3.x to address this issue, as well as giving more typed models using fragments as interfaces. 
The default `operationBased` models will correctly merge the merged fields in the output json. Additionally, you can look into `responseBased` models ([doc](https://www.apollographql.com/docs/android/v3/advanced/response-based-codegen/)) to model fragments as interfaces.

Any chance you can try the just released [`3.0.0-rc01`](https://github.com/apollographql/apollo-android/releases/tag/v3.0.0-rc01) and let us know what you think?

**Comment by mateuszkwiecinski** [comment] 2021-12-12 01:27
I think I faced exactly the same issue in `3.0.0-rc02`. Repro test: https://github.com/mateuszkwiecinski/apollo-playground/blob/979d9f9d7070aaf584a6899b360445b550b25885/src/test/kotlin/com/example/Test.kt#L87

(`nested response` test passes on 2.x but fails on 3.0.0-rc02 with `Object 'viewerId.nested({"limit":1}).0.books.0' has no field named 'id'` 

and it seems like there is a behavior change between 2.x and 3.x and 3.x 🤔  2.x seems to pick _first_ fragment, 3.x picks _last_ fragment (which in my case results `id` being dropped which breaks caching heavily.

|Apollo 2.x|Apollo 3.x|
|---|---|
|![image](https://user-images.githubusercontent.com/36954793/145697024-d96f3beb-2093-464e-b757-902aef9c400c.png)|![image](https://user-images.githubusercontent.com/36954793/145697019-5d8b5194-443f-49cb-9151-692a8c93009a.png)|

**Comment by mateuszkwiecinski** [comment] 2021-12-12 02:54
Feel free to ignore my comment from above. It seem like I stumbled upon yet another issue where superflous field in json response was written into the cache, which seems to be fixed 3.x. 

Here's proper repro on 3.0.0-rc02 for both this issue and #2818: https://github.com/mateuszkwiecinski/apollo-playground/blob/7c5ae7530511bb872a7b04694a0a9423b8757555/src/test/kotlin/com/example/Test.kt#L15

3.0.0-rc02 tries to read all requested field and throws `CacheMiss` in runtime.
2.5.11 seems to drop additional fragment data since the very beginning, so at least it's easy to spot something's wrong by looking at generated models, but the app remains _stable_

3.0.0-rc02 doesn't fix merged fragments issue and it seems it introduces regression to how they behave in 2.5.11

**Comment by martinbonnin** [comment] 2021-12-12 18:54
Thanks a lot for the reproducer, that helps a ton 💙 ! 

Turns out there was a bug in `BufferedSinkJsonWriter` that did not correctly merge nested objects. This should work now with https://github.com/apollographql/apollo-android/pull/3691. I took the liberty of adding your test case to the test suite ([here](https://github.com/apollographql/apollo-android/pull/3691/files#diff-ac25d0407b2f2a7f9a1f6da9a085df7d6eb4652f9453f78bcbd9937e187d0182R32)) so we don't have this happening again, let me know if it's ok with you.

As a side note, if you have a lot of [merged fields](https://spec.graphql.org/draft/#sec-Field-Selection-Merging) like `book` here, you might also be interested in `responseBased` codegen (doc [here](https://www.apollographql.com/docs/android/v3/advanced/response-based-codegen/)). It's a codegen that "flattens" the fragments and generates models matching 1:1 with the json response (instead of matching the GraphQL query). While it usually generates more code, it also generates models that don't have to rewind at all so the parsing is usually faster. Which one to use is a tradeoff so that why we included both but sounds like it could help for this specific use case.

**Comment by mateuszkwiecinski** [comment] 2021-12-13 09:04
🎉  
It's great to hear all of that! That's the kind of new one wants to read in the morning 🚀 

>let me know if it's ok with you.

Sure! I probably could have adding tests in this project in the first place to make it even easier. Thanks! 

>As a side note, if you have a lot of merged fields like book here, you might also be interested in responseBased codegen

Nice, didn't know that 👍  I don't think I have that many merged fields in my _default_ project (I only aimed to try all types of them in the repro), but I'll definitelly try that out and see if there's any profit, thanks again!

**Comment by martinbonnin** [comment] 2021-12-14 12:09
This is fixed in `3.0.0-rc03`. Closing this issue.

**Comment by mateuszkwiecinski** [comment] 2021-12-15 09:07
@martinbonnin 👋 I think I found another edge case where `rc-03` doesn't work if the nested fragment references a list of objects 👀

Here's updated repro: https://github.com/mateuszkwiecinski/apollo-playground/tree/fragments_with_lists
The test fails with `Object 'library-1.books.0' has no field named 'id'` despite the referenced `book` has an id and if I'm not mistaken it should be properly picked by `CacheKeyGenerator`
When looking at the cache content, I expected to see a book id in following places:
<img width="482" alt="Screenshot 2021-12-15 at 10 04 26" src="https://user-images.githubusercontent.com/36954793/146156436-352cdc27-9d42-458c-b23a-26a626ac648a.png">

I tried to modify the functional test you've added, but I'm having trouble to set-up the project on Java17 :/ (btw I think I made a mistake previously when declaring [CacheResolver](https://github.com/apollographql/apollo-kotlin/blob/5a9d189d825c92d9e07c9cc98bfe49f54ae1b48a/tests/normalization-tests/src/test/kotlin/com/example/NormalizationTest.kt#L28) I should have used the one [migration guide](https://www.apollographql.com/docs/kotlin/migration/3.0/#caching) suggests (it doesn't affect the previous repro, but it seems to be important now, so I updated [it's definition](https://github.com/mateuszkwiecinski/apollo-playground/blob/59a296cd5e2980512f2a0f228bce7b9a2111333e/src/test/kotlin/com/example/IdBasedCacheKeyResolver.kt#L13)))

**Comment by martinbonnin** [comment] 2021-12-20 17:54
Fixed in 3.0.0, hopefully for good 🤞

**Closed by martinbonnin** 2021-12-20 17:54 UTC
Labels: :beetle: Type: Bug

**Comment by tlevavasseur** [comment] 2021-12-20 18:01
I'm not 100% done migrating to 3.0.0 (rc3) but for my initial problem it's ok

**Comment by mateuszkwiecinski** [comment] 2021-12-21 17:59
Hello 👋 It's me again 😬 
I think I found one more edge case which seems to be a behavior change when compared with 2.x: https://github.com/mateuszkwiecinski/apollo-playground/tree/cross_cache_typename - (this specific branch)
The only test there throws:
> Object 'book-id' has no field named '__typename'

And if I'm not mistaken the repro is to have 2 queries, first writes data into cache, the other one tries to fetch part of the previous object, but it uses fragments as a part of its definition. 

If I inline the `bookData` fragment the test passes which makes me think that might be an unwanted behavior.

**Comment by martinbonnin** [comment] 2022-01-06 13:59
Hi @mateuszkwiecinski and apologies for huge Holidays delay. Wish you and everyone in this thread all the best for 2022 🎄  :)

This issue is somewhat different because the underlying cause is the algorithm used to add `__typename`.

In a nutshell, the 3.x code adds `__typename` when there are fragment (because this is how you do polymorphism in GraphQL and when we need `__typename` to parse to the correct concrete type). 

This is more restrictive than 2.x that added it on all composite fields by default.

Overall, we're trying to remove the unneeded added `__typename` because it's less bytes on the network, less work to parse and overall leaner models (see also [this issue](https://github.com/apollographql/apollo-kotlin/issues/1458)). So I don't think we want to rollback to 2.x behaviour there.

What we can do is add an optimization that doesn't add typename if we know by construction that the fragment type condition is always true (i.e. the field is monomorphic). This will not fix all issues. For an example, someone could do this:

```graphql
interface Product
type Book implements Product

# read from network
query Query1 {
  book {
    id # "1001"
    title
  }
}

# read from cache

query Query2 {
  product(id: "1001")  {
    ... on Book {
      id
      title
    }
  }
}
```

`__typename` is not needed to parse `Query1` but it is for `Query2` so we'd have to store the mapping of `id` <-> `__typename` somewhere in the cache. That's doable but not easy.

All in all:

* quick workaround: add `__typename` to `GetAuthor.viewer.author.topBook` so that the cache can find it
* mid-term: optimize and do not add `__typename` for monomorphic fields
* long-term: store the `id` <-> `__typename` mapping in the cache

**Comment by lwasyl** [comment] 2022-01-07 07:22
It's great to have this optimization, always fetching `__typename`s was a bit of a waste 🎉 

I just wanted to point out that the current behavior makes it pretty easy to shoot yourself in the foot, because intuitively fragment extraction like from this:

```graphql
query Foo {
  foo {
    bar
    baz
  }
}
```
to this:
```graphql
query Foo {
  foo { 
    ...fooData 
  }
}

fragment fooData on Foo {
  bar
  baz
}
```
shouldn't be a functional change. It's really easy to not realize that Apollo will fetch different data in both cases and thus cause potential case misses. Perhaps it'd be worth documenting this somehow?

**Comment by martinbonnin** [comment] 2022-01-10 14:30
@lwasyl indeed. One more argument to remove the `__typename` in these cases. Let's follow up in #3774
