### ISSUE TITLE
[umbrella issue] Java Runtime

### ISSUE THREAD

**Issue by martinbonnin** [apollographql/apollo-kotlin#3694] opened 2021-12-13 16:06 UTC
Now that `apollo-runtime` brings `kotlinx.coroutines` as a dependency, it's not as easy to work with interceptors, etc.. in Java because everything is a `Flow` or `suspend` function.

This issue is to gather interest about writing an alternative runtime that can reuse a lot of the common parts (`apollo-api`, normalization, cache, etc...) but expose a coroutine-free runtime. 

* [x] #4388
* [x] #4389
* [x] #4392
* [ ] #4394
* [x] #4390
* [x] #4391
* [ ] #4395
* [ ] #4396
* [x] #4393
* [x] #4397

**Comment by kicktipp** [comment] 2022-01-14 17:22
I would love to see better java support. At least it should be documented how to use the lib with java. I tried yesterday to upgrade to 3.0 but failed.

**Comment by MatthewFrench** [comment] 2022-02-01 05:36
Same, I'm seeing problems using apollo Optional.Absent and graphql query errors like `Type parameter '...Data' is not within its bound; should implement 'com.apollographql.apollo3.api.Operation.Data'`.

**Comment by martinbonnin** [comment] 2022-02-01 08:18
Hi @MatthewFrench ! Do you have sample code/a reproducer? Maybe we can fix this one without implementing a separate coroutine-free Java runtime.

**Comment by BoD** [comment] 2022-04-01 07:14
Hi @cristian1980 👋 

Currently the recommended way to use Apollo Kotlin from Java is through the RxJava adapters, which are described [here](https://www.apollographql.com/docs/kotlin/advanced/rxjava). Basically you would do something like:

```java
Single<ApolloResponse<GetAppConfigQuery.Data>> queryResponse = Rx2Apollo.single(
        apolloClient.query(new GetAppConfigQuery())
);
queryResponse.subscribe( 
        response -> {
          // Use response
        },
        throwable -> {
          // Handle error
        }
);
```

**Comment by brendanlong** [comment] 2022-05-06 00:56
I'm using Rx3Apollo and it works for me in gradle but I get the same error in Intellij:

<img width="1099" alt="Screen Shot 2022-05-05 at 6 51 15 PM" src="https://user-images.githubusercontent.com/1447206/167049436-87e6bd9b-f273-4921-891f-c7ae6dbd2c7a.png">

<img width="1143" alt="Screen Shot 2022-05-05 at 6 51 28 PM" src="https://user-images.githubusercontent.com/1447206/167049474-79e38492-9f87-4519-9512-5d8eb6b8d05c.png">

Weirdly enough, it works fine when I build on the command line with Gradle, so it's possible something weird is going on in Intellij?

If I manually edit my generated file and change:

```
public static class Data implements Mutation.Data {
```

to:

```
public static class Data implements Mutation.Data, Operation.Data {
```

... everything works, but I don't know why that would matter since Mutation.Data supposedly already extends Operation.Data.

<img width="807" alt="Screen Shot 2022-05-05 at 6 56 10 PM" src="https://user-images.githubusercontent.com/1447206/167049725-25b00ca4-a9a7-4326-8916-c43d66e4f68a.png">

I almost never use Java so it's possible I'm missing something obvious here, but wanted to document it in case other people are having this problem too.

**Comment by BoD** [comment] 2022-05-06 09:07
Hi @brendanlong 👋 

I don't seem to reproduce the issue on a simple project (with IntelliJ IDEA 2022.1). But seeing that it works on the command line, this would indeed seem to be some kind of issue with IntelliJ.

**Comment by kkunan** [comment] 2022-05-14 05:19
One possible solution for people who really need to use Java here, is to create a wrapper class. 
It requires mixing with Kotlin a little bit.

1. Create ApolloWrapper.kt, similar to this
```
fun <D: Query.Data> query(client: ApolloClient,
                          query: Query<D>,
                          listener: QueryApolloResponseListener<D>){
    CoroutineScope(Dispatchers.IO).launch {
        val response = client.query(query).execute()
        response.data?.let {
            listener.onSuccess(it)
        } ?: kotlin.run {
            listener.onFailure(response.errors ?: emptyList())
        }

    }
}

fun <D: Mutation.Data> mutate(client: ApolloClient,
                              mutation: Mutation<D>,
                              listener: MutationApolloResponseListener<D>){
    CoroutineScope(Dispatchers.IO).launch {
        val response = client.mutation(mutation).execute()
        response.data?.let {
            listener.onSuccess(it)
        } ?: kotlin.run {
            listener.onFailure(response.errors ?: emptyList())
        }

    }
}

interface QueryApolloResponseListener<T: Query.Data> {
    fun onSuccess(data: T)
    fun onFailure(error: List<com.apollographql.apollo3.api.Error>)
}

interface MutationApolloResponseListener<T : Mutation.Data> {
    fun onSuccess(data: T)
    fun onFailure(error: List<com.apollographql.apollo3.api.Error>)
}
```

2. In your java file, do something like this

```
public void call(){
        ApolloClient client = new ApolloClient.Builder()
                .serverUrl("https://apollo-fullstack-tutorial.herokuapp.com/graphql")
                .build();
        LoginMutation mutation = new LoginMutation("testEmail");
        ApolloWrapperKt.mutate(client, mutation, new ResponseListener());
    }

    static class ResponseListener implements MutationApolloResponseListener<LoginMutation.Data> {
        @Override
        public void onSuccess(@NonNull LoginMutation.Data data) {
            System.out.println(data);
        }

        @Override
        public void onFailure(@NonNull List<Error> error) {
            System.err.println(error);
        }
    }

```

So far the compiler haven't complained and I got the response back correctly.

**Comment by stengvac** [comment] 2022-06-20 21:05
> Type parameter '...Data' is not within its bound; should implement 'com.apollographql.apollo3.api.Operation.Data'

This probably is not Apollo problem. I have tried some combinations. Kotlin generated classes work fine in Java classes in same gradle module, it seems this is broken when those are made as dependencies and only for IDE - project still compile and is runnable so it is Idea bug?

**Comment by jpvajda** [comment] 2022-10-21 17:14
Hello everyone! Thanks for raising this concern on our support of Java. We appreciate the feedback. 🙏 

We are trying to better understand the use of Java with our Kotlin Client, and wanted to ask : 

Are any of you using Java for Mobile Android development, or is this something else all together? Any additional information would help us tremendously to better understand your use cases here. Thank you!

**Comment by kicktipp** [comment] 2022-10-21 17:55
We are not using for Android mobile.  We are using it as a Java  client for a graphql backend.  We never used kotlin before.

**Comment by stengvac** [comment] 2022-10-24 13:21
Hello,

We are using it as client between BE services. Some of them are written in Java and https://youtrack.jetbrains.com/issue/IDEA-296915 make it hard to use generated Kotlin client. Once this issue is gone (should be with Kotlin compiler 1.8) then we can swap to Kotlin.

**Comment by jpvajda** [comment] 2022-10-24 17:28
@kicktipp and @stengvac thank you for responding!

**Comment by maclockard** [comment] 2023-03-13 17:08
I have nearly the same use case as @stengvac. IDE support, lack of documentation, and lack of an easy to use java runtime is making the migration to 3.x quite tricky.

**Comment by bignimbus** [comment] 2023-09-29 14:20
We think that our experimental Java support is feature-complete for the 4.0.0 release, the remaining tasks have not yet been prioritized.  We'll keep them open but in the interest of keeping our task list clean we'll close this umbrella Issue.

**Closed by bignimbus** 2023-09-29 14:20 UTC
Labels: :sparkles: Type: Feature
