### ISSUE TITLE
Gradle build cache issues: Sometimes a CustomType is not generated

### ISSUE THREAD

**Issue by francescocervone** [apollographql/apollo-kotlin#2043] opened 2020-03-06 13:48 UTC
**Summary**
Sometimes a `CustomType` is not generated.

**Description**
Not sure if it helps, but the custom scalar is named `Uuid` in the schema.
The only way to workaround this issue is:
- run `./gradlew :broken-module:clean`
- run `rm -rf ~/.gradle/caches`
- run `./gradlew :broken-module:assemble` again

Running just `:broken-module:clean` task does not help. 
Switching from Kotlin to Java models does not help.

I still don't understand when this happen. I can work for hours or days without any issue and *sometimes* when I touch that module (even without changing any apollo file), this issue appears.

**Version**
I'm pretty sure this issue was introduced in Apollo 1.3.\*.
I'm currently using Apollo 1.3.2.

**Comment by sav007** [comment] 2020-03-06 19:25
Are you using new or deprecated Apollo gradle plugin?

@martinbonnin Could it be gradle plugin issue?

**Comment by francescocervone** [comment] 2020-03-06 19:35
We are using the new gradle plugin `com.apollographql.apollo`.

**Comment by martinbonnin** [comment] 2020-03-07 19:28
Is only `CustomType` missing or all the generated sources as well ?

**Comment by francescocervone** [comment] 2020-03-07 20:18
I haven't checked it actually, I will next time it happens, but I can say for sure that the `CustomType` enum class is generated with all other custom scalars except `UUID`.

**Comment by martinbonnin** [comment] 2020-03-07 20:29
Interesting. So `CustomType.kt` is always generated but sometimes it's missing the `UUID` scalar type while all the other are present ?

That definitely look like a caching issue. Not really sure what could be the root cause though. Do you have several modules using apollo and maybe it's reusing the output of a wrong module ?

**Comment by francescocervone** [comment] 2020-03-07 20:35
>Interesting. So CustomType.kt is always generated but sometimes it's missing the UUID scalar type while all the other are present ?

Exactly

>That definitely look like a caching issue. Not really sure what could be the root cause though. Do you have several modules using apollo and maybe it's reusing the output of a wrong module ?

Just one module using Apollo.

**Comment by martinbonnin** [comment] 2020-03-07 20:51
I've seen cases where my cache was corrupted too. A few other things to try:

* Bump your gradle version to the latest version (6.2.2 right now), just in case some gradle bug was fixed in between.
* Next time this happens, run with `-i`: `./gradlew :module:generateApolloSource -i` that'll show if the task was cached and if cached, what cache key is used. If it turns out to be a cache issue, maybe we could get the input parameter from a cache key.

**Comment by francescocervone** [comment] 2020-03-07 21:15
We already have Gradle 6.2.2.
I will run the task with `-i` next time this happens. Thanks.

**Comment by francescocervone** [comment] 2020-03-18 08:30
I investigated more about the issue.
I wasn't able to reproduce it but I think I understood some kind of pattern, because it is happening something similar now. It must be some caching issue.

The issue I described before happened when I switched between branches. I had a branch (let's call it `new-feature-branch`) that added a new query `QueryX` that had an argument of type `UUID`. Apollo generated that parameter in order to make me use it. When I switched to `master` branch, the `CustomTypes` generated class was correctly generated without `UUID` (because on master it wasn't used), but the `QueryX` generated class of `new-feature-branch` was still there, like the query was still defined in a `.graphql` file. That caused the compile task of that module to fail because there was an unresolved reference to `CustomTypes.UUID`.

Now, something similar happened. I just renamed a query from `query X` to `query Y` and the generated `X` class is still there. Even if I run `:module:clean` and `:module:generateApolloSources` it is restored from cache.

This is the output of `:module:generateApolloSources -i` after a clean:
```
> Task :networking:generateDebugAndroidTestServiceApolloSources NO-SOURCE
Task :networking:generateDebugAndroidTestServiceApolloSources in networking Starting
file or directory '/Users/francesco/AndroidStudioProjects/prima-android/networking/src/androidTest/graphql', not found
file or directory '/Users/francesco/AndroidStudioProjects/prima-android/networking/src/androidTestDebug/graphql', not found
Skipping task ':networking:generateDebugAndroidTestServiceApolloSources' as it has no source files and no previous output files.
Task :networking:generateDebugAndroidTestServiceApolloSources in networking Finished
:networking:generateDebugAndroidTestServiceApolloSources (Thread[Execution worker for ':',5,main]) completed. Took 0.001 secs.
:networking:generateDebugAndroidTestApolloSources (Thread[Execution worker for ':',5,main]) started.

> Task :networking:generateDebugAndroidTestApolloSources UP-TO-DATE
Task :networking:generateDebugAndroidTestApolloSources in networking Starting
Skipping task ':networking:generateDebugAndroidTestApolloSources' as it has no actions.
Task :networking:generateDebugAndroidTestApolloSources in networking Finished
:networking:generateDebugAndroidTestApolloSources (Thread[Execution worker for ':',5,main]) completed. Took 0.0 secs.
:networking:generateDebugServiceApolloSources (Thread[Execution worker for ':',5,main]) started.

> Task :networking:generateDebugServiceApolloSources FROM-CACHE
Task :networking:generateDebugServiceApolloSources in networking Starting
Build cache key for task ':networking:generateDebugServiceApolloSources' is 086244e9f5a81c155c1f05f8a4841763
Task ':networking:generateDebugServiceApolloSources' is not up-to-date because:
  Output property 'outputDir' file /Users/francesco/AndroidStudioProjects/prima-android/networking/build/generated/source/apollo/debug/service has been removed.
  Output property 'outputDir' file /Users/francesco/AndroidStudioProjects/prima-android/networking/build/generated/source/apollo/debug/service/it has been removed.
  Output property 'outputDir' file /Users/francesco/AndroidStudioProjects/prima-android/networking/build/generated/source/apollo/debug/service/it/prima has been removed.
Loaded cache entry for task ':networking:generateDebugServiceApolloSources' with cache key 086244e9f5a81c155c1f05f8a4841763
Task :networking:generateDebugServiceApolloSources in networking Finished
:networking:generateDebugServiceApolloSources (Thread[Execution worker for ':',5,main]) completed. Took 0.05 secs.
:networking:generateDebugApolloSources (Thread[Execution worker for ':',5,main]) started.

> Task :networking:generateDebugApolloSources UP-TO-DATE
Task :networking:generateDebugApolloSources in networking Starting
Skipping task ':networking:generateDebugApolloSources' as it has no actions.
Task :networking:generateDebugApolloSources in networking Finished
:networking:generateDebugApolloSources (Thread[Execution worker for ':',5,main]) completed. Took 0.0 secs.
:networking:generateDebugUnitTestServiceApolloSources (Thread[Execution worker for ':',5,main]) started.

> Task :networking:generateDebugUnitTestServiceApolloSources NO-SOURCE
Task :networking:generateDebugUnitTestServiceApolloSources in networking Starting
file or directory '/Users/francesco/AndroidStudioProjects/prima-android/networking/src/test/graphql', not found
file or directory '/Users/francesco/AndroidStudioProjects/prima-android/networking/src/testDebug/graphql', not found
Skipping task ':networking:generateDebugUnitTestServiceApolloSources' as it has no source files and no previous output files.
Task :networking:generateDebugUnitTestServiceApolloSources in networking Finished
:networking:generateDebugUnitTestServiceApolloSources (Thread[Execution worker for ':',5,main]) completed. Took 0.0 secs.
:networking:generateDebugUnitTestApolloSources (Thread[Execution worker for ':',5,main]) started.

> Task :networking:generateDebugUnitTestApolloSources UP-TO-DATE
Task :networking:generateDebugUnitTestApolloSources in networking Starting
Skipping task ':networking:generateDebugUnitTestApolloSources' as it has no actions.
Task :networking:generateDebugUnitTestApolloSources in networking Finished
:networking:generateDebugUnitTestApolloSources (Thread[Execution worker for ':',5,main]) completed. Took 0.0 secs.
:networking:generateReleaseServiceApolloSources (Thread[Execution worker for ':',5,main]) started.

> Task :networking:generateReleaseServiceApolloSources FROM-CACHE
Task :networking:generateReleaseServiceApolloSources in networking Starting
Build cache key for task ':networking:generateReleaseServiceApolloSources' is e671985def2add7e592176f3ec229583
Task ':networking:generateReleaseServiceApolloSources' is not up-to-date because:
  Output property 'outputDir' file /Users/francesco/AndroidStudioProjects/prima-android/networking/build/generated/source/apollo/release/service has been removed.
  Output property 'outputDir' file /Users/francesco/AndroidStudioProjects/prima-android/networking/build/generated/source/apollo/release/service/it has been removed.
  Output property 'outputDir' file /Users/francesco/AndroidStudioProjects/prima-android/networking/build/generated/source/apollo/release/service/it/prima has been removed.
Loaded cache entry for task ':networking:generateReleaseServiceApolloSources' with cache key e671985def2add7e592176f3ec229583
Task :networking:generateReleaseServiceApolloSources in networking Finished
:networking:generateReleaseServiceApolloSources (Thread[Execution worker for ':',5,main]) completed. Took 0.062 secs.
:networking:generateReleaseApolloSources (Thread[Execution worker for ':',5,main]) started.

> Task :networking:generateReleaseApolloSources UP-TO-DATE
Task :networking:generateReleaseApolloSources in networking Starting
Skipping task ':networking:generateReleaseApolloSources' as it has no actions.
Task :networking:generateReleaseApolloSources in networking Finished
:networking:generateReleaseApolloSources (Thread[Execution worker for ':',5,main]) completed. Took 0.0 secs.
:networking:generateReleaseUnitTestServiceApolloSources (Thread[Execution worker for ':',5,main]) started.

> Task :networking:generateReleaseUnitTestServiceApolloSources NO-SOURCE
Task :networking:generateReleaseUnitTestServiceApolloSources in networking Starting
file or directory '/Users/francesco/AndroidStudioProjects/prima-android/networking/src/test/graphql', not found
file or directory '/Users/francesco/AndroidStudioProjects/prima-android/networking/src/testRelease/graphql', not found
Skipping task ':networking:generateReleaseUnitTestServiceApolloSources' as it has no source files and no previous output files.
get insurances and saved quotes
Task :networking:generateReleaseUnitTestServiceApolloSources in networking Finished
:networking:generateReleaseUnitTestServiceApolloSources (Thread[Execution worker for ':',5,main]) completed. Took 0.0 secs.
:networking:generateReleaseUnitTestApolloSources (Thread[Execution worker for ':',5,main]) started.

> Task :networking:generateReleaseUnitTestApolloSources UP-TO-DATE
Task :networking:generateReleaseUnitTestApolloSources in networking Starting
Skipping task ':networking:generateReleaseUnitTestApolloSources' as it has no actions.
Task :networking:generateReleaseUnitTestApolloSources in networking Finished
:networking:generateReleaseUnitTestApolloSources (Thread[Execution worker for ':',5,main]) completed. Took 0.0 secs.
:networking:generateApolloSources (Thread[Execution worker for ':',5,main]) started.

> Task :networking:generateApolloSources UP-TO-DATE
Task :networking:generateApolloSources in networking Starting
Skipping task ':networking:generateApolloSources' as it has no actions.
Task :networking:generateApolloSources in networking Finished
:networking:generateApolloSources (Thread[Execution worker for ':',5,main]) completed. Took 0.0 secs.
```

I hope this helps.

**Comment by francescocervone** [comment] 2020-03-26 13:48
A similar issue occurred also while upgrading Apollo to 1.4.1.
I believe that with the new Apollo version some internal classes were moved to `com.apollographql.apollo.api.internal` package, but some generated classes are still referencing `com.apollographql.apollo.api`. 
That makes me think that once again those generated sources are picked from cache instead of being generated.
Deleting `~/.gradle/caches` fixed the issue again.

This is an example of generated a class after upgrading to Apollo 1.4.1.
<img width="782" alt="Schermata 2020-03-26 alle 14 42 02" src="https://user-images.githubusercontent.com/6197796/77653886-9381d080-6f70-11ea-8da6-69b201835bb8.png">

**Comment by martinbonnin** [comment] 2021-12-08 11:39
Hi 👋 
Can someone try if the same thing happens with [Apollo Android 3](https://github.com/apollographql/apollo-android/releases/tag/v3.0.0-rc01)? Lots of things have changed in the Gradle plugin so I'm hoping this is something of the past...

**Closed** 2022-02-08 09:54 UTC
Labels: :beetle: Type: Bug, Type: Investigation, :hourglass:  waiting for info
