### ISSUE TITLE
Stuck in constant query loop

### ISSUE THREAD

**Issue by giantramen** [apollographql/apollo-kotlin#2226] opened 2020-04-28 15:26 UTC
**Summary**
I have two different queries that return the same data fragment (cached by id) that changes every time it is fetched from the server. When one query completes it causes the other query to fire again and gets into a never-ending loop. 

**Description**

I have a schema that has something like this:
Site
..[Photo]

Gallery
..[Photo]

Example: 
I fetch a site with a photo with id "1", and then I fetch a gallery which returns the same photo with id "1" but with some different data, the site query fires again and returns photo with id "1" and then it causes the gallery query to fire, repeat indefinitely. 

Am I doing something wrong? 
Why do the queries fire again when the underlying data changes, shouldn't it just update in cache?

**Version**
1.4.5 / 2.0.0
I did not see this issue in 1.2.0

**Comment by giantramen** [comment] 2020-04-28 15:43
Ah, I have to set refetchResponseFetcher on the watcher to CACHE_ONLY.
Shouldn't that be the default?

**Comment by sav007** [comment] 2020-05-01 00:36
strange, as default fetcher for watchers is `ApolloResponseFetchers.CACHE_FIRST` so it should hit cache first and skip network if there is data in cache.

**Comment by martinbonnin** [comment] 2020-08-25 11:09
Is this issue still valid? @giantramen can you share your queries and how you are executing them (coroutines, rxjava, callback, etc...)? Also, do you use a CustomKeyResolver?

**Comment by nicusorflorin** [comment] 2020-08-26 12:26
this happens to be too, but my use case is more complicated and so i cannot provide queries. I use coroutines 
this is my keyresolver

```

class DefaultCacheKeyResolver : CacheKeyResolver() {

    override fun fromFieldArguments(field: ResponseField, variables: Operation.Variables): CacheKey {
        return formatCacheKey(field.resolveArgument("id", variables) as? String)
    }

    override fun fromFieldRecordSet(field: ResponseField, recordSet: Map<String, Any>): CacheKey {
        return formatCacheKey(recordSet["id"] as? String)
    }

    private fun formatCacheKey(id: String?): CacheKey {
        return if (id == null || id.isEmpty()) {
            CacheKey.NO_KEY
        } else {
            CacheKey.from(id)
        }
    }

}


```

**Comment by martinbonnin** [comment] 2020-08-26 12:54
@nicusorflorin if you get a chance, it would be interesting to investigate why there's a cache miss. The process is not straightfoward at the moment and we should definitely make it easier (see https://github.com/apollographql/apollo-android/issues/2397). But you should be able to get some information about the missing key (if any) by adding breakpoints to CacheFieldValueResolver: https://github.com/apollographql/apollo-android/blob/905620cd98dfb5cbb07b5a540558c1cc761c45e1/apollo-normalized-cache/src/commonMain/kotlin/com/apollographql/apollo/cache/normalized/internal/CacheFieldValueResolver.kt#L42

**Comment by nicusorflorin** [comment] 2020-08-26 14:18
@martinbonnin i'm getting  ```Missing value:  outer({"first":150}) ```

**Comment by martinbonnin** [comment] 2020-08-26 14:23
Thanks. It might be the pagination parameters that trigger the cache miss. I'll try to reproduce.

**Comment by nicusorflorin** [comment] 2020-08-26 14:48
There aren't any except the "first" tried with a page size of "2" and it happens even more often

**Comment by martinbonnin** [comment] 2020-08-26 15:02
> There aren't any except the "first" tried with a page size of "2" and it happens even more often

Not sure I get it. There aren't any cache miss? Or are pagination parameters always the same?

**Comment by nicusorflorin** [comment] 2020-08-27 06:59
for the main query the one that gets looped they are always the same. only a page size is specified via the "first" parameter

**Comment by Nealsoni00** [comment] 2020-09-03 12:44
I'm encountering a similar infinite refresh loop on the watcher when a query returns two objects of the *same type* with the *same id*. ex:
```query FetchBuildings() {
   user { 
        id 
        primaryBuilding {
             ...buildingFields
        }
        buildings {
             ...buildingFields
        }
   }
} ```

I'm using the ID cache system since all objects are fetched with a UUID. When I comment out ```primaryBuilding``` the query and watchers work as normal. Even when I set it to ```CACHE_ONLY``` it fetches network as per the profiler. The returned response every time the watcher is called (5-6 times a second) is correct. 

Been stuck on this issue for a while, would love any help!

**Comment by Nealsoni00** [comment] 2020-09-03 13:18
Hi Martin, The one difference I see is that I have a different query run on the initialization of the application (before the main page appears). That query has the same data as the FetchBuildingsQuery and a lot more (initializing user app state, etc).

**Comment by martinbonnin** [comment] 2020-09-03 13:31
How many watchers do you have ultimately? I feel like this issue should only happen with two watchers? And the initialization query you're doing doesn't seem like a good candidate to be a watcher. Or is it?

**Comment by Nealsoni00** [comment] 2020-09-03 13:33
I commented out all other watchers in the entire application. That is the only one that is left.

**Comment by martinbonnin** [comment] 2020-09-03 13:50
I see, it's the same query being watched from different places. Well that's unexpected given that's exactly what my reproducer does. Maybe it's a timing issue somewhere, having a reproducer somewhere would be super useful.

**Comment by roum** [comment] 2022-07-06 21:43
@Nealsoni00 I know this thread is old but did you resolve your issue? I'm encountering the same problem where a `CACHE_ONLY` watcher seemingly triggers a network request and I can't figure out why.

**Comment by Nealsoni00** [comment] 2022-07-06 21:50
> @Nealsoni00 I know this thread is old but did you resolve your issue? I'm encountering the same problem where a `CACHE_ONLY` watcher seemingly triggers a network request and I can't figure out why.

Sorry have since moved off native android. I vaguely remember it being solved by ensuring the retuned data only returned an object with ID XXXXX once. (No fetching same object more than once).

**Comment by martinbonnin** [comment] 2024-03-21 09:00
Hello everyone 👋 This issue is quite the oldie and I'm not sure how to move forward without a reproducer. I'm going to close it for now but if anyone wants to deep dive in this again, please feel free to leave a comment and I'll reopen.

**Closed by martinbonnin** 2024-03-21 09:00 UTC
Labels: :bug: Type: Bug, :mag:  Type: Investigation
