### ISSUE TITLE
Unit tests: Cannot access class (in fragment package)

### ISSUE THREAD

**Issue by Eselfar** [apollographql/apollo-kotlin#5365] opened 2023-11-10 19:10 UTC
### Version

3.8.2

### Summary

I try to run one of my test class which includes references to classes generated by Apollo
If I run the tests the first time it works. Subsequent times fail with an error (see Logs section).
If I clean the project first every time I want to run the tests, then it's working. Of course it's not a solution as rebuilding everything every time is quite time consuming.

My Apollo configuration is like this (following the documentation):
```
apollo {
    service("service") {
        packageName = "{package id}"
    }
}
```
The `packageName` matches the the app id and the project packages for the source files.

My configuration is as below:
```
    javaVersion = JavaVersion.VERSION_17
    jvmTargetVersion = 17
    kotlinVersion = '1.8.22'
    kotlinLanguageVersion = '1.7'
```

Also I'm using `.gradle` files (Groovy DSL), not `.gradle.kts` (Kotlin DSL) as the project hasn't been migrated yet.

Issue, as describe is with unit tests only. The rest works as expected.

### Logs

```
Cannot access class '{package id}.fragment.{class}'. Check your module classpath for missing or conflicting dependencies
```

**Comment by martinbonnin** [comment] 2023-11-10 19:39
Thanks for filing this. I [tried to reproduce](https://github.com/martinbonnin/test-fragment-from-tests) with no success so far. Might be due to Java - Kotlin interop if you're using Java? Can you share what task is failing? Also any chance you can change the [reproducer](https://github.com/martinbonnin/test-fragment-from-tests) to reproduce the issue?

**Comment by AlexanderAltena92** [comment] 2023-12-07 00:49
Im experiencing the same in our project (we have a multimodule setup, where graphQl has its own module on wich other modules depend).  I was able to repoduce it locally by tweaking the reproducer a bit I can open a branch on the reproducer to showcase the error?

**Comment by AlexanderAltena92** [comment] 2023-12-07 09:06
Update here is a repo I made (dont mind the messy setup it was just to showcase the potential bug)

https://github.com/AlexanderAltena92/no-access-bug

**Comment by martinbonnin** [comment] 2023-12-07 10:19
I can reproduce, thanks. 

```
 ./gradlew :mylibrary2:testDebugUnitTest
# uncomment `succeeding access test`
 ./gradlew :mylibrary2:testDebugUnitTest
```

output:

```
> Task :mylibrary2:compileDebugUnitTestKotlin FAILED
e: file:///Users/mbonnin/git/no-access-bug/mylibrary2/src/test/java/com/example/mylibrary2/FailingUnitTest.kt:22:42 Cannot access class 'com.example.mylibrary2.fragment.UserDetails.Address'. Check your module classpath for missing or conflicting dependencies
```

**Comment by aaaleem** [comment] 2023-12-12 07:57
any work around for now?

**Comment by AlexanderAltena92** [comment] 2023-12-12 10:04
The only option I found was duplicating the fragment related code in the unit-test (so your mapping logic Fragment.toModel() etc.), this defeats the whole puropose of unit tests but its better than no unit tests at al 🫥
Enums can be accessed fine so no need to add those to the unit test

**Comment by martinbonnin** [comment] 2023-12-13 10:18
This looks like a [Kotlin incremental compilation](https://kotlinlang.org/docs/gradle-compilation-and-caches.html#incremental-compilation) issue. Can you try disabling it by adding `kotlin.incremental=false` to your `gradle.properties`?

```
# gradle.properties
kotlin.incremental=false
```

**Comment by martinbonnin** [comment] 2023-12-13 10:47
Also looks like this is fixed in Kotlin `2.0.0-Beta.1` 🎉 

See https://github.com/AlexanderAltena92/no-access-bug/pull/1

**Comment by AlexanderAltena92** [comment] 2023-12-13 11:11
> This looks like a [Kotlin incremental compilation](https://kotlinlang.org/docs/gradle-compilation-and-caches.html#incremental-compilation) issue. Can you try disabling it by adding `kotlin.incremental=false` to your `gradle.properties`?
> 
> ```
> # gradle.properties
> kotlin.incremental=false
> ```

Ill check it after lunch, so Ill have an answer for you around 14:00ish 🙏. 

Thanks for all the effort, really appreciate it

**Comment by AlexanderAltena92** [comment] 2023-12-13 12:45
You can slap a fixed on this badboy it works 💪

Would you mind telling me how you figured out it was the incremental issue?

And once again thnx for the effort

**Comment by martinbonnin** [comment] 2023-12-13 13:27
Glad to hear that 🎉 Thanks for the follow up! TBH I'm not really sure how I figured it out. 

I guess I spent enough hours/days/weeks debugging those kind of build issues that stuff like this comes to mind now 😅

**Closed by martinbonnin** 2023-12-13 13:27 UTC
Labels: :bug: Type: Bug, :hourglass:  Waiting for info
