### ISSUE TITLE
Custom scalar does not allow generics

### ISSUE THREAD

**Issue by cvb941** [apollographql/apollo-kotlin#6156] opened 2024-09-20 12:35 UTC
### Version

4.0.0

### Summary

I'm trying to setup an adapter for a Mass measurement from a float.

`mapScalar("Mass", "io.nacular.measured.units.Measure<Mass>", "data.apollo.MassAdapter")`

Notice that the target class has a type parameter. 

Gradle sync fails with the following error:
```Can't escape identifier `Measure<Mass>` because it contains illegal characters: <>```

This is the adapter (for completeness):
```kotlin
val MassAdapter = object : Adapter<Measure<Mass>> {
    override fun fromJson(reader: JsonReader, customScalarAdapters: CustomScalarAdapters): Measure<Mass> {
        val weightDouble = reader.nextDouble()
        return weightDouble.asMass(Mass.baseUnit)
    }

    override fun toJson(writer: JsonWriter, customScalarAdapters: CustomScalarAdapters, value: Measure<Mass>) {
        writer.value(value.`in`(Mass.baseUnit))
    }
}
```

### Logs

```
(Your logs here)
```

**Comment by BoD** [comment] 2024-09-20 16:32
Thanks for reporting this! We may be able to support this in the future but in the meantime a simple solution is to use a typealias:

```kotlin
typealias MassMeasure = Measure<Mass>
```

```kotlin
mapScalar("Mass", "data.apollo.MassMeasure", "data.apollo.MassAdapter")
```

**Comment by martinbonnin** [comment] 2024-09-23 10:25
Closing as a duplicate of https://github.com/apollographql/apollo-kotlin/issues/3243

**Comment by martinbonnin** [comment] 2024-10-16 08:16
(forgot to close) 
this will be available in next release, closing now.

**Closed by martinbonnin** 2024-10-16 08:16 UTC
Labels: :gear: Codegen, :bug: Type: Bug
