### ISSUE TITLE
Subscription switched to DISCONNECTED

### ISSUE THREAD

**Issue by legend-egy** [apollographql/apollo-kotlin#2765] opened 2020-11-21 17:36 UTC
**Summary**
After subscription is opened with 1 min or so it switched to Disconnected 

**Background**
I added one subscription into my project to listen for new events coming from graphQL server 
I found out that sometimes events is not received in the app however . if i am listening to subscriptions from GraphQl Playground  i am able to see the events there !!

**How i was sure that this is a bug**
I started to log the state for the subscription using the following listener  
`  apolloClient.subscriptionManager.addOnStateChangeListener { fromState, toState -> }`

What i found is the following states are triggered  : 
`DISCONNECTED ->  CONNECTING  -> CONNECTED -> ACTIVE`
and i actually receive events but 
After 1 min or 2 mins it is directly changed to  `DISCONNECTED`  without going to `Stopping` or `Stopped`
and in this state i don't receive any events 

**Version**
2.4.4

**MyCode**

[1] setup

```
 val okHttpClient = okHttpClient.newBuilder().addInterceptor { chain ->
      val request = chain.request().newBuilder().apply {
        addHeader("Authorization", storage.accessToken())
      }.build()
      chain.proceed(request)
    }.build()
    
    val subscriptionTransportFactory =
      WebSocketSubscriptionTransport.Factory(envType.socketUrl(), okHttpClient)

    val authenticationParams = hashMapOf("Authorization" to storage.accessToken(),)

    return ApolloClient.builder()
      .serverUrl(baseUrl())
      .okHttpClient(okHttpClient)
      .subscriptionConnectionParams(SubscriptionConnectionParams(authenticationParams))
      .subscriptionTransportFactory(subscriptionTransportFactory)
      .build()
```

[2] 

`  suspend fun subscribeToNewsEvents() =
    apolloClient.subscribe(NewsEventsSubscription()).toFlow()
      .map { it.data!!.NewsEvents!! }
`

[3] i am collecting this flow in the activity 

**My Question**
[1] why it is disconnected after being Active ?
[2] how i can know the cause of this issue or log it ?
[3] how to overcome this because this a really blocking issue preventing us from releasing our app ?

Please let me know if i am not clear for the bug

**Comment by martinbonnin** [comment] 2020-11-21 18:11
Hi! Thanks for the detailed report. Maybe the authorisation token is expired? Is your GraphQL playground public so I could take a look by any chance? 

To answer your questions:

> [1] why it is disconnected after being Active ?

I guess something closed the websocket, most likely on the server but it might be on the client too.

> [2] how i can know the cause of this issue or log it ?

Can you intercept the Websocket traffic with Charles Proxy? That should give you a good idea of who's closing the connection and if there are any unusual messages being transfered.

> [3] how to overcome this because this a really blocking issue preventing us from releasing our app ?

A workaround would be to use `Flow.retry` to reconnect automatically if the connection drops.

If it's authorisation related, you can also take a look at [apolloClient.subscriptionManager.reconnect()](https://github.com/apollographql/apollo-android/issues/2702#issuecomment-717390887) for how to update the authorization parameters

**Comment by elgendyLanes** [comment] 2020-11-21 21:33
Hi Martin , 

First of all many thanks for your quick reply. 

Unfortunately the playGround is not public but i can ensure that if i open a connection to playground and on same time 
i am using the app : in playground it is not disconnected at all , always alive but in app it disconnected.

Regarding the the token expiration it is not expired because i tried to do pull to refresh or do any requests and token is working fine.

Regarding your answer for 
`A workaround would be to use Flow.retry to reconnect automatically if the connection drops.`

1] is there is a way to Log exception when it is disconnected to find what it the issue ? 
Or intercept traffic using Charles Proxy will do the trick ??

2] should i use flow.retry OR apolloClient.subscriptionManager.reconnect() if this case happened ?

3] using `subscriptionHeartbeatTimeout` is useful for this case or it useless ? 
or what the purpose of heartBeat in subscription ?

**Comment by legend-egy** [comment] 2020-11-21 21:34
Hi Martin , 

First of all many thanks for your quick reply. 

Unfortunately the playGround is not public but i can ensure that if i open a connection to playground and on same time 
i am using the app : in playground it is not disconnected at all , always alive but in app it disconnected.

Regarding the the token expiration it is not expired because i tried to do pull to refresh or do any requests and token is working fine.

Regarding your answer for 
`A workaround would be to use Flow.retry to reconnect automatically if the connection drops.`

1] is there is a way to Log exception when it is disconnected to find what it the issue ? 
Or intercept traffic using Charles Proxy will do the trick ??

2] should i use flow.retry OR apolloClient.subscriptionManager.reconnect() if this case happened ?

3] using `subscriptionHeartbeatTimeout` is useful for this case or it useless ? 
or what the purpose of heartBeat in subscription ?

**Comment by martinbonnin** [comment] 2020-11-21 22:42
Hi! II think using `Flow.retry` is the quickest workaround here to reconnect when you get disconnected. Something like:

```
suspend fun subscribeToNewsEvents() = apolloClient.subscribe(NewsEventsSubscription()).toFlow().retry().map { it.data!!.NewsEvents!! }
```

There might also be something to investigate around the heartbeat but without a way to reproduce it's going to be difficult. It might be similar to this bug https://github.com/apollographql/apollo-android/issues/2733 that I wanted to investigate. I'll post some progress there if I find anything.

**Comment by legend-egy** [comment] 2020-11-22 15:13
Great i will be waiting your investigation results 👍

**Comment by martinbonnin** [comment] 2020-11-22 17:58
Sounds good. Just a heads up that it might take some time since I'm not super familiar with the subscription code. Also that [other issue I linked](https://github.com/apollographql/apollo-android/issues/2733) is maybe completely different so if you need a short term solution, I'd recommend the `retry` workaround

**Comment by legend-egy** [comment] 2020-11-23 16:24
@martinbonnin  i totally understand take your time 👍  

I just want to inform you that `[retry]` will work if exception is thorwn other than that it will not do retry 
so one short term solution is to `[reconnect] `

So i can use `reconnect()` 
for example 

```
    apolloClient.subscriptionManager.addOnStateChangeListener { fromState, toState ->
         if(toState = SubscriptionManagerState.DISCONNECTED) {
        //reconnect and passing the SubscriptionConnectionParams(authenticationParams)
      }
    }
```
i would like in case of disconnection try at least to connect again , how i can pass the SubscriptionConnectionParams to `reconnect()`  method  ?

**Comment by moshkit** [comment] 2020-12-28 09:53
I think i have faced with similar problem
 - If you loose and restore connection, subscription will not be restored.

The problem lives here [here](https://github.com/apollographql/apollo-android/blob/8a160f57845cb9c5d009660017a11820be3f7a5c/apollo-coroutines-support/src/main/kotlin/com/apollographql/apollo/coroutines/CoroutinesExtensions.kt#L168l)

So on any error channel will be closed, and you will never recieves notifications on client.

You have to handle errors in subscription inside flow [Apollo docs](https://www.apollographql.com/docs/android/tutorial/11-subscriptions/#handle-errors)

You should use `retryWhen`

**Comment by danielehrhardt** [comment] 2021-01-15 22:19
> So on any error channel will be closed, and you will never recieves notifications on client.

Did you solved it?

**Comment by moshkit** [comment] 2021-01-28 19:01
> > So on any error channel will be closed, and you will never recieves notifications on client.
> 
> Did you solved it?

 My temporary solution here. Rewrite toFlow extension.

**Comment by omeraslam-citrusbits** [comment] 2021-03-05 11:01
Any update on this, I am also facing same problem.

**Comment by Jazeb** [comment] 2021-07-12 07:05
i am also facing this issue on https server URL but on ip it works fine. Subscription disconnects after 1 min on https url but not on IP, not sure if it might be the issue with nginx.

**Comment by martinbonnin** [comment] 2024-03-12 21:48
Anyone still around with this issue? It's been a while but `4.0.0-beta.5` introduces a new approach to retrying the subscriptions at the `ApolloClient` layer:

```kotlin
    ApolloClient.Builder()
        .serverUrl(sampleServer.graphqlUrl())
        .retryOnError { it.operation is Subscription }
        .subscriptionNetworkTransport(
            WebSocketNetworkTransport.Builder()
                .serverUrl(sampleServer.subscriptionsUrl())
                .build()
        )
        .build()
```

If anyone's get a chance to try it, I'm eager to know what you think. If not, and since this issue is almost 3 years old now, I'll close it and anyone reading this should feel free to open a new one.

**Comment by martinbonnin** [comment] 2024-04-29 15:44
Closing. See https://github.com/apollographql/apollo-kotlin/issues/5862 for follow ups.

**Closed by martinbonnin** 2024-04-29 15:44 UTC
Labels: :bug: Type: Bug, :calling: Subscriptions
