### ISSUE TITLE
Kotlin/JS - JsonEncodingException: Unterminated string at path

### ISSUE THREAD

**Issue by maribelmai** [apollographql/apollo-kotlin#4222] opened 2022-06-23 19:43 UTC
**Summary**
In Kotlin/JS - JsonEncodingException: Unterminated string at path [<specified_path_of_string_field>] when trying to parse a String value

**Version**
3.3.2

**Description**
I tested with several APIs and I keep getting
```
"JsonEncodingException: Unterminated string at path [<specified_path_of_string_field>]
    at syntaxError (webpack-internal:///./kotlin/kotlin_com_apollographql_apollo3_apollo_api.js:6833:12)
    at nextQuotedValue (webpack-internal:///./kotlin/kotlin_com_apollographql_apollo3_apollo_api.js:6440:15)
    at BufferedSourceJsonReader.nextString_kwkc9o_k$ (webpack-internal:///./kotlin/kotlin_com_apollographql_apollo3_apollo_api.js:7413:17)
    at readAny (webpack-internal:///./kotlin/kotlin_com_apollographql_apollo3_apollo_api.js:8269:33)
    at readAny (webpack-internal:///./kotlin/kotlin_com_apollographql_apollo3_apollo_api.js:8282:72)
    at readAny (webpack-internal:///./kotlin/kotlin_com_apollographql_apollo3_apollo_api.js:8301:34)
    at readAny (webpack-internal:///./kotlin/kotlin_com_apollographql_apollo3_apollo_api.js:8282:72)
    at Companion_6.buffer_f9k3tr_k$ (webpack-internal:///./kotlin/kotlin_com_apollographql_apollo3_apollo_api.js:8679:15)
    at ObjectAdapter.fromJson_vznj7e_k$ (webpack-internal:///./kotlin/kotlin_com_apollographql_apollo3_apollo_api.js:470:39)
```
when the library tries to parse a String value

It's a Kotlin Multiplatform project and the same code works fine in Android.

Could this be a bug or a misconfiguration? Any help is appreciated. TIA

**Comment by martinbonnin** [comment] 2022-06-23 23:05
Hi 👋 Can you share the Json you're trying to parse? If you can't share it publicly, feel free to send it at martin@apollographql.com.

**Comment by martinbonnin** [comment] 2022-06-27 18:46
Many thanks for the follow up 🙏 ! I'm going to close this issue since you have a working solution. If you ever have a reproducer or want us to investigate more, feel free to comment below. This might be a chunked-encoding issue or something similar.

**Closed by martinbonnin** 2022-06-27 18:46 UTC
