### ISSUE TITLE
apollo-kotlin client throws IllegalStateException for large numbers

### ISSUE THREAD

**Issue by itd-sk** [apollographql/apollo-kotlin#4994] opened 2023-05-26 08:54 UTC
### Version

3.8.1

### Summary

The apollo-kotlin client handles large numbers differently than the nodeJs Apollo Federation Server and the Kotlin GraphQL Server. This can cause the apollo-kotlin client to throw an exception when parsing the JSON response with large numbers, even though the number is a valid number for the federation and the GraphQL server.

I think that this is a bug in the apollo-kotlin client, as there should be no check if the long value can be converted to a double value, as in the JavaScript federation service the value is represented differently than in Kotlin. The apollo-kotlin client throws an exception in this case, although it is a valid GraphQL response.

### Steps to reproduce the behavior

- The Kotlin GraphQL Server sends a JSON response to the federation service with the number 8.9894366197183136e+16
- The federation parses the JSON and responses to the apollo-kotlin client with a different representation of the number: 89894366197183140
- The apollo-kotlin client interprets this number as Long even if it is a GraphQL Float scalar. The function `MapJsonReader.nextDouble() 
    ...
       when (val value = peekedData) { 
          ... 
          is Long -> value.toDoubleExact()
          ...
      }
   ...`
throws an exception because 89894366197183140 != 8.9894366197183136e+16.
- If the federation service would send the number as  89894366197183140.0 the apollo-kotlin client would not throw an exception.

**Comment by BoD** [comment] 2023-05-26 09:40
Hi! Thank you for reporting this.

The issue is that the value `89894366197183140` cannot be represented as a Kotlin Double (double-precision 64-bit IEEE 754 floating point number), and that is why `toDoubleExact` is failing. I think we want to keep this behavior because it ensures correctness - i.e. returning an incorrect value could lead to subtle bugs at a higher level of your application, that would be hard to pinpoint.

I am wondering why Federation transforms the float representation into an integer, and we probably would want to avoid that - unless there is a good reason to do so that I'm not aware of. Can I ask what version of Gateway or Router (or something else) you are using for Federation?

**Comment by martinbonnin** [comment] 2023-06-21 08:56
Hi @itd-sk. Do add on @BoD comment above, the [GraphQL draft](https://spec.graphql.org/draft/#sec-Float.Result-Coercion) is explicit about not coercing Float values that could lose information:

From https://spec.graphql.org/draft/#sec-Float.Result-Coercion:

> GraphQL services may coerce non-floating-point internal values to Float when reasonable without losing information, otherwise they must raise a [field error](https://spec.graphql.org/draft/#field-error).

Closing this issue. If you give us your Gateway/Router version, we'll chase down internally what could cause the issue.

**Closed by martinbonnin** 2023-06-21 08:56 UTC
Labels: :bug: Type: Bug, :hourglass:  Waiting for info
