### ISSUE TITLE
Changing Unit Test In Anyway Creates a Failed Run of Tests

### ISSUE THREAD

**Issue by grndvl1** [apollographql/apollo-kotlin#4568] opened 2022-12-09 16:31 UTC
### Summary

Just by adding something simple as a new line the Junit test run using Bradley testDebugJunitTest will fail with this odd error.  So basically change any test code in a Unit test will fail.  You have to clean rebuild every time.

### Version

3.7.0 - 3.7.2

### Steps to reproduce the behavior

Go to any Unit test class and add a newline
run test
test fails with 
e: /android/ui/sell/wizard/step2/SellCarFeaturesStep2ViewModelTest.kt: (208, 42): Cannot access class 'my.apollo.type.UserVehicleIntake'. Check your module classpath for missing or conflicting dependencies

### Logs

```
(Your logs here)
```

**Comment by BoD** [comment] 2022-12-09 16:51
Hi! I don't seem to be able to reproduce this on a simple project. Is there any way you could share a project that can showcase the issue?

**Comment by martinbonnin** [comment] 2022-12-13 15:51
@grndvl1 anything else we can help with here?

**Comment by martinbonnin** [comment] 2022-12-16 14:11
Closing this one as it's unclear what can be done from Apollo's side. Feel free to leave a comment if you want me to reopen.

**Closed by martinbonnin** 2022-12-16 14:11 UTC
Labels: :bug: Type: Bug, :hourglass:  Waiting for info

**Comment by martinbonnin** [comment] 2023-02-08 10:15
@grndvl1 and everyone starring this issue, turns out we were able to reproduce in #4669. Go there for more details and workarounds
