### ISSUE TITLE
gradle source generation is failed by .graphql .graphqls unnecessary enforcement  

### ISSUE THREAD

**Issue by nort3x** [apollographql/apollo-kotlin#4586] opened 2022-12-15 21:11 UTC
### Summary

my approach toward keeping my client(s) synced with my server is by using `git submodule` and having server schema sources as a separate module in both `apollo-react-client` and `apollo-kotlin-client` (i'm using springboot for the server)

nowhere it is enforced that i have to use `.graphqls` extension for my schemas, i know it is mentioned in this project that:

Apollo Kotlin supports three types of files:

* .graphqls schema files: describes the types in your backend using the GraphQL syntax.
* .json schema files: describes the types in your backend using the Json syntax.
* .graphql executable files: describes your queries and operations in the GraphQL syntax.

okay but i had no issue with writing and keeping my schema files with `.graphql` in both `server` and `apollo-react-client`
and i assume it's not something enforced by graphql protocol or even guidelines, but the gradle source generation goal will fail on dealing with .graphql as follows

```kotlin
apollo {
    generateKotlinModels.set(true)

    val graphqlSources = mutableListOf<String>()
    fileTree("${baseDir}/something/graphql-server/").visit {
        if (this.name.endsWith(".graphql")) // notice it's not graphqls
            graphqlSources.add(this.file.path)
    }
    schemaFiles.setFrom(graphqlSources)
}
```
it could not understand `extend type Query`  in one of the sources and fails, this is not expected.

### Version

3.5.0

### Logs

```
(Your logs here)
```

**Comment by martinbonnin** [comment] 2022-12-15 21:30
Hi 👋 

Good point. I guess we could just parse everything and handle operation and type definitions inside the compiler itself. The reason for separate extensions is mostly historical. We'll look into this.

In the short term, your best bet is to identify the schema with its full name. Assuming your schema is named `schema.graphql`, you should be able to do something like this:

```kotlin
apollo {
  // Set the schema
  schemaFiles.setFrom(
      file("${baseDir}/something/graphql-server/").walk()
          .filter { it.name == "schema.graphql" }
  )

  // Set the regular operation files
  srcDir("${baseDir}/something/graphql-server/") 
  excludes.add("**/schema.graphql")
}
```

**Comment by martinbonnin** [comment] 2023-02-28 15:23
I'm going to close this one as "working as intended". There is quite some brain muscle around schemas with `.graphqls` extensions and the current Gradle APIs that I don't want to risk changing this, especially since there are workarounds. Plus there are some advantages to this separation: more granular Gradle tasks checking, more tooling opportunities, etc... If anyone feels strongly about this, please leave a comment and we'll revisit.

**Closed by martinbonnin** 2023-02-28 15:23 UTC
Labels: :bug: Type: Bug
