### ISSUE TITLE
'responseBased' models do not support @include/@skip and @defer directives on fragments

### ISSUE THREAD

**Issue by ynkm169** [apollographql/apollo-kotlin#4481] opened 2022-10-30 00:04 UTC
Hello!
Is there a way to set the following and still have ability to specify @include / @skip directives?
`codegenModels.set("responseBased")`

For us, it is essential to have "responseBased", but also @include directive. Kinda feel stuck

**Comment by martinbonnin** [comment] 2022-10-30 15:26
Hi 👋 

You can use `@include`/`@skip` on individual fields:

```graphql
query GetHero($withDetails: Boolean!) {
  hero {
    name 
    ... on Droid {
       # This is working
       primaryFunction @include(if: $withDetails)
    }
  }
}
```

You can not use it on fragments:


```graphql
query GetHero($withDetails: Boolean!) {
  hero {
    name 
    # This is **not** working
    ... on Droid @include(if: $withDetails) {
       primaryFunction 
    }
  }
}
```

The reason is that every include directive on fragments multiplies by 2 the number of generated models and complexifies the codegen and usages to a point where we weren't sure it was worth it. Using `@include`/`@skip` on individual fields has been an acceptable workaround until now. If it is not for your use case, do you mind ellaborating more and that will help prioritize work on this?

**Comment by ynkm169** [comment] 2022-10-30 16:07
Hi thanks so much for providing the info! That’s massively helpful!

To provide more context, I am working on a large app that has a complex model.

1. it has 200+ fields/sub fields
2. The model is used and shared by between 40-100 feeds. A feed contains paginated list of this model. Different feed request different mix of these fields and sub fields to be efficient.
3. Our app is very sensitive to performance implications, hence we want to keep it as response based.

Say the model is called Hero. The feed contains list of heros.

I am trying to find a way for the code gen to generate a common model like this

```

Interface Hero: HeroSubfieldsGroup1, HeroSubfieldsGroup2 {
    100 fields override
}

interface HeroSubfieldsGroup1 {
    50 fields inside
}

interface HeroSubfieldsGroup2 {
    50 fields inside
}
```

so that I could have 1 UI view to display a hero for 40-100 feeds where each feed request only some parts of the model. Without a common model, I have to duplicate 100 of view classes like this HeroView1, HeroView2… to accept different model shape.
```
Class HeroView {
     show(hero: Hero){
        hero.field1?.let {
              label1 = hero.field1
         }
         hero.field100?.let {
              label100 = hero.field100
         }
     }
}
```

Now with directive I could do the following. Otherwise my query needs to contain 200+ booleans. And I since we have 40-100 feeds, it will be 40-100 queries each with 200+ Boolean arguments.
```
HeroQuery($showSubfielfsGroup1: Boolean!,  $showSubfieldsGroup2:Boolean!) {
     … HeroSubfieldsGroup1 @include(if: $showSubfielfsGroup1)

 … HeroSubfieldsGroup2 @include(if: $showSubfielfsGroup2)
}

Fragment HeroSubfieldsGroup1: Hero {
  50 fields
}
Fragment HeroSubfieldsGroup1: Hero {
  50 fields
}
```

question
1. If above can be supported, will it generate a common model or not? I typed what I images the code gen would generate (the hero interface) but I am not so sure that’s the case.
2. How does 10 Boolean arguments affect codegen, performance and caching? What if it is 200 Booleans?

**Comment by martinbonnin** [comment] 2022-10-30 18:07
Thanks for all the context! If I'm understanding correctly, you have a schema like this:

```graphql
interface Hero {
  id: ID!
  name: String!
  field1: String!
  field2: String!
  # ... lots of additional fields
  friends: [Hero!]!
}

type HumanHero implements Hero {
  # same fields as Hero
  age: Int!
  height: Float!
  # ... lots of additional field definitions
}

# lots of additional Hero type definitions

type SomeOtherHero implements Hero {
  # same fields as Hero
  someOtherField: Int!
  yetAnotherFields: Float!
  # ... lots of additional field definitions
}

type Feed {
  heroes: [Hero!]!
}

type Query {
  feed: Feed!
}
```

And a query like this:

```graphql
query GetFeed($withDetails1: Boolean!, $withDetails2: Boolean!) {
  feed {
    id 
    name
    # other fields 
    ... on Hero @include(if: $withDetails1) {
      field1
      # other fields
    }
    ... on Hero @include(if: $withDetails2) {
      field2
      # other fields
    }
  } 
}
```

Am I correct? If that's the case, you can use `operationBased` codegen and it will generate models like this (details omitted):

```kotlin
class Hero(
  val id: String,
  val name: String,
  ...
  val onHeroIfWithDetails1: OnHeroIfWithDetails1?,
  val onHeroIfWithDetails2: OnHeroIfWithDetails2?
)

class OnHeroIfWithDetails1(val field1: String, ...)
class OnHeroIfWithDetails2(val field2: String, ...)
```

Then you can have a view that handles `Hero` and depending if `onHeroIfWithDetails1` is null or not, display the additional details (same with `onHeroIfWithDetails2`)

That should perform similarly to retrofit as long as you don't have any merged fields i.e. the fields you put inside withDetails1 do not overlap with the other ones.

**Comment by ynkm169** [comment] 2022-10-30 18:43
> Then you can have a view that handles Hero and depending if onHeroIfWithDetails1 is null or not, display the additional details (same with onHeroIfWithDetails2)
That's exactly what I was hoping for. When I looked at code gen doc I hypothesized that operationBased would work. Thanks for confirming.

> That should perform similarly to retrofit as long as you don't have any merged fields i.e. the fields you put inside withDetails1 do not overlap with the other ones.
That's exactly what I imagined as well!
However, I never mentioned operationBased, because operationBased looked too good in comparison, though I have no evidence/testing/AB testing to confirm.
> They save some memory: they don't have to buffer the whole network response in an intermediate HashMap
> They save cpu cycles: because they don't have to write and read the intermediate HashMap, the parsing is slightly more efficient
> Most importantly, they can amortize building the models during network I/O: once the last byte of data is received, the models are ready to be consumed.

Our schema is like the following, we don't have polymorphic models. 
interface SuperObject {
 id: ID!
}
type Hero implements SuperObject {
    #no HumanHero or SomeOtherHero
}

Depending on the feed, we request sub sets of the fields of Hero. We only have Hero interface and no HumanHero. On top of my head it maybe not feasible at all to introduce polymorphic models due to shear size of our app and BE. That is why we'd need ton of @include directives. Even with operationBased, we'd still need possibly 100+ of @include inside Hero. This is concerning due to:
1. possible performance impact
2. query in .grpahql file would explode due to the need to specify 100+ boolean arguments.
3. I mentioned 100+ @include because I am trying to avoid merge fields. To reduce @include, I'd have to do the following, but that would introduce too many duplicate fields.
```
Query (){
  … HeroSubfieldsGroup1 @include(if: $isFeedType1)

  … HeroSubfieldsGroup1 @include(if: $isFeedType2)

  … HeroSubfieldsGroup1 @include(if: $isFeedType30)
}
```
This is what would look like if I try to avoid duplicate fields.
Query ($includeField1: Boolean = false, $includeField2: Boolean = false, ...... $includeField100: Boolean = false){
    ... on Hero {
         field1 @include(if: $includeField1)
         field2 @include(if: $includeField2)
         # many fields
         field100 @include(if: $includeField100)
    }
}
```



The end game solution for us I Imagine being moving to completely polymorphic, and we may get away with bare minimum and in some cases 0 include directives. (operationBased performance is still a concern but I guess we have no choice on that end)

I revised your example a little.
```
interface Hero ....
type HumanHero implements Hero ....
type SomeOtherHero implements Hero ....

query GetFeed($withDetails1: Boolean!, $withDetails2: Boolean!) {
  feed {
    id 
    # other fields 
   hero {
      ... on HumanHero  {
        humanField1
        # other fields
      }
      ... on SomeOtherHero  {
        someOtherHeroField1
        # other fields
      }
    }
  } 
}
```

**Comment by ynkm169** [comment] 2022-10-30 19:06
### Summary of my previous post
**ResponseBased**
It would not work for us since the generated interfaces have no common shape. Following is [example generated interface](https://github.com/apollographql/apollo-kotlin/blob/main/design-docs/Codegen.md) from official tutorial of polymorphic types
```
interface Hero(val id: String)
interface DroidDetails(val primaryFunction: String)
```
**OperationBased**
If we do not implement polymorphic types, there will be 
1. performance concerns due to merged fields
2. If we avoid merged fields, will introduce issue of massive number of @include. This is both problematic in terms of code bloat/maintenance and performance of number of @include directives

**Comment by ynkm169** [comment] 2022-10-31 04:00
I think there was some misunderstanding. I could actually do this for responseBased and problem solved. There are a lot of @include, but there are only 2 arguments.

```
HeroQuery($showSubfielfsGroup1: Boolean!,  $showSubfieldsGroup2:Boolean!) {
  … HeroSubfieldsGroup1

 … HeroSubfieldsGroup2 @include(if: $showSubfielfsGroup2)
}

Fragment HeroSubfieldsGroup1: Hero {
  field1 @include(if: $showSubfielfsGroup1)
  field100 @include(if: $showSubfielfsGroup1)
}
Fragment HeroSubfieldsGroup2: Hero {
 field1 @include(if: $showSubfielfsGroup2)
  field100 @include(if: $showSubfielfsGroup2)
}
```

**Comment by AdamMTGreenberg** [comment] 2022-11-01 17:08
I could lend my support for the desire for inclusion of `@include`/`@skip` on `responseBased` models. It would help us with "dynamically" build queries at runtime.

**Comment by ynkm169** [comment] 2022-11-01 20:50
Encountered a Null pointer exception in XXQuery_ResponseAdapter.kt
If I remove this line, it will work. If I leave it there, exception will be thrown at run time.
`...SomeFragment`

```
HeroQuery($flag1: Boolean!,  $flag2:Boolean!) {
  hero {
   … HeroSubfieldsGroup1
  }
 }

Fragment HeroSubfieldsGroup1: Hero {
  field1 @include(if: $flag1) {
       subField1
       subField2
  }
 field1 @include(if: $flag2) {
       subField3
       subField4
  }
  field1 @include(if: $flag3) {
       subField5
       subField6
       ...SomeFragment
  }
}
```

**Comment by ynkm169** [comment] 2022-11-01 21:15
^^ turned out the exception was caused by SomeFragment having a field "type"
```
Fragment SomeFragment: Field1Type {
     type
}
```

**Comment by ynkm169** [comment] 2022-11-01 22:20
^^ looks like it's not apollo issue. Our schema definition for id is
id: ID!
I will delete these to make this thread clean

**Comment by martinbonnin** [comment] 2022-11-02 09:51
Hi 👋 , If you have a minimal reproducer for the crashes, I can investigate those. In general, I wouldn't put a `@include` directive on the `__typename` field as it's required for polymorphic parsing. Maybe that's what's happening there.

About `@include` in `responseBased` codegen, I want to set expectation that if we ever end up implementing it, any query using it will double the size of the codegen because we'll have to generate two different models:

Query:
```graphql
query GetHero($withDetails: Boolean!) {
  hero {
    name
    ... on Character @include(if: $withDetails) {
      appearsIn
    }
  }
}
```

Models:
```kotlin
sealed interface Hero(val name: String)
class HeroWithDetails(val name: String, val appearsIn: Episode): Hero
class OtherHero(val name: String): Hero
```

That's a simple example but nested fields and fragment spread can generate a lot of code.

**Comment by ynkm169** [comment] 2022-11-02 14:34
If there are 10 includes, and we pass in 2^10 combinations of true/false values, it will generate 2^10 models?

**Comment by ynkm169** [comment] 2022-11-02 14:57
The arguments of true/false are passed at run time. The model generation is offline, how would model generation knows value of true/false?

**Comment by martinbonnin** [comment] 2022-11-02 15:05
> would it be possible to generate just 1 model but with the fragment having a value of null if include is false?

That's exactly what `operationBased` models do. Because fragments have a corresponding synthetic field, the synthetic fragment field can be set to null.

The same thing cannot be done with `responseBased` models because fragments do not have a synthetic field and therefore cannot be "null". If the fragment is present, we will parse to a model implementing the fragment interface and if not, to another model. Which means the codegen has to take into account all cases.

**Comment by martinbonnin** [comment] 2023-07-06 13:27
Given that the maintenance/benefit ratio isn't great and to keep the issue list lean, I'm going to close this one as `Not Planned`. If anything comes up that may change the ratio (new Kotlin language features maybe, new approach to codegen or something else?) feel free to leave a comment and we'll reopen.

**Closed by martinbonnin** 2023-07-06 13:27 UTC
