### ISSUE TITLE
r8 issue when enabling multi-module support and using `alwaysGenerateTypesMatching(...)`

### ISSUE THREAD

**Issue by theBradfo** [apollographql/apollo-kotlin#3979] opened 2022-03-30 21:29 UTC
**Summary**
Experiencing r8 issues after adding `alwaysGenerateTypesMatching(...)` to a project to prepare for multi-module support.

**Version**
`3.1.0`

**Description**
We are adding our _second_ gradle module that contains a GraphQL operation that apollo-api will generate models with.  With the introduction of this module, we found apollo to be generating duplicate types from the schema, which resulted in a fairly immediate build failure.  Adding `alwaysGenerateTypesMatching.set(["type1", "type2"])` to our apollo config fixed this issue with multi-modules 🎉, however post-merge of this single line change (that prepared for the future module(s)) developers started to experience dex issues at build time:

```
    Caused by: com.android.tools.r8.internal.b: Type <company package>.type.<type1>$Companion is defined multiple times: /<workspace/project>/build/projects/<feature>/graphql/.transforms/98fe7e52668cfdca9482dea7a49a29d0/transformed/main/<company package>/type/<type1>$Companion.dex, /<workspace/project>/build/projects/<company package>/schema/.transforms/6521f7d4cc59cf29f8f5e374c4ec6815/transformed/main/<company/package>/type/<type1>$Companion.dex
        at com.android.tools.r8.internal.il1.a(SourceFile:14)
        at com.android.tools.r8.internal.il1.a(SourceFile:22)
        at com.android.tools.r8.internal.lf1.b(SourceFile:6)
        at com.android.tools.r8.internal.lf1.a(SourceFile:23)
        at com.android.tools.r8.internal.lf1.a(SourceFile:10)
        at java.base/java.util.concurrent.ConcurrentHashMap.merge(ConcurrentHashMap.java:2048)
```
To reproduce, we:
1) Do not have this `alwaysGenerateTypesMatching` present in the apollo config, assemble the app, any flavor, i.e. `:app:assembleDebug`
2) Add this `alwaysGenerateTypesMatching` config, rerun that same gradle command
3) Observe the above r8 exception.

It seems after adding this config, we need to force gradle to rebuild all apollo modules, is there a good way to enforce this?  I believe changing the `version` string in the `OperationIdGenerator` will have this effect, but would be good to know if there's a better way and potentially update the documentation 😄

**Comment by martinbonnin** [comment] 2022-03-30 21:45
Thanks for sending this! 

> We are adding our second gradle module [...]
> With the introduction of this module, we found apollo to be generating duplicate types from the schema

That's unexpected. `alwaysGenerateTypesMatching` is mainly to be used when 3 schemas or more are involved. Sibling modules don't have information about what types are generated in the sibling and this is what causes duplicates. 

In the 2 modules cases, I think it shouldn't happen? Do you mind sharing the error you have before you add `alwaysGenerateTypesMatching` ?

**Comment by theBradfo** [comment] 2022-03-30 22:05
Yeah so we do actually have 3 modules (and intend on having _n_ modules very soon!):
- schema module
- feature module hosting query 1
- feature module hosting query 2 <-- in introducing this, we ran into the issue that `alwaysGenerateTypesMatching` fixes.

**Comment by martinbonnin** [comment] 2022-03-30 22:22
Ah gotcha! Makes sense. I would expect in that case that the metadata json file generated by the schema module changes, which should trigger a new run of the codegen which in each feature module. This in turn should remove the duplicate classes from the dex files 🤔

It'd be interesting to run Gradle with `-i` and check what task are considered up-to-date. Maybe it's the codegen task but the metadata files are listed as inputs so it _should_ work. Might be another task down the graph maybe?

**Comment by theBradfo** [comment] 2022-03-31 13:09
Thanks for the quick replies Martin! I'm working in an enormous project, so I can't really provide the entire output of this, but, for the relevant `feature1:graphql` module, this is what is output: 
```
> Task :<feature1>:graphql:generateServiceApolloSources UP-TO-DATE
Build cache key for task ':<feature1>:graphql:generateServiceApolloSources' is 0202e2f4fe453ac158a77a2623475bf6
Skipping task ':<feature1>:graphql:generateServiceApolloSources' as it is up-to-date.
:<feature1>:graphql:generateServiceApolloSources (Thread[Execution worker for ':' Thread 11,5,main]) completed. Took 0.005 secs.
```
And this is the reproducible case as above where we have only one feature module containing an operation, and another module hosting the schema - the intermediary step before we introduce our second feature module hosting a graphql operation.  

So a couple of questions on this:
1) Is there a good way to force apollo to rebuild the relevant modules after adding this config?  I believe changing the `version` string in the `OperationIdGenerator` should have this effect, but seems weird to modify this given its seemingly unrelated to the change.
2) Should `alwaysGenerateTypesMatching(...)` only be introduced _with_ the follow-up change that introduces the second module hosting a graphql operation?

**Comment by martinbonnin** [comment] 2022-03-31 16:47
Are you able to reproduce from the command line? I can reproduce from Android Studio using the green triangle but not from the command line.

**Comment by theBradfo** [comment] 2022-03-31 16:49
Yeah, I was reproducing from command line only (our project discourages project builds through AS).

**Comment by martinbonnin** [comment] 2022-03-31 16:50
What task are you running? `assemble`?

**Comment by theBradfo** [comment] 2022-03-31 17:05
I'm building with `assemble<Flavor>Debug` in this case.

**Comment by martinbonnin** [comment] 2022-03-31 17:09
Thanks. Reproducer project: https://github.com/martinbonnin/r8bug. I somehow can't reproduce on the command line there. Not sure why. I'll keep looking

Other things to try:
- disabling the build cache
- updating the AGP version

**Comment by theBradfo** [comment] 2022-03-31 17:15
FWIW i'm able to get around this issue locally if i delete my `build/` directory, and rerun the relevant `assemble<Flavor>Debug` task with `--no-build-cache`.  Unfortunately for the project I'm working with and the number of developers involved its an infeasible ask 😞

**Comment by kenyee** [comment] 2022-03-31 18:42
@martinbonnin why is this line commented out?
https://github.com/martinbonnin/r8bug/blob/master/schema/build.gradle.kts#L16

**Comment by martinbonnin** [comment] 2022-03-31 18:46
@kenyee my current understanding of the bug is that you need to:

1. click the green triangle in Android Studio
2. uncomment the line that enables `alwaysGenerateTypesMatching`
3. click the green triangle in Android Studio again
4. get the error about duplicate classes in the dex files

IIUC, the bug doesn't show if you start a clean build with the `alwaysGenerateTypesMatching` line  uncommented

**Comment by martinbonnin** [comment] 2022-04-01 11:27
Tried several things and the only way I can reproduce is using Android Studio (either BumbleBee or Dolphin) and clicking the green triangle. Downgrading AGP to 4.2.2 fixes the issue. `7.1.0` and `7.3.0-alpha07` have the issue. 

If you could somehow tweak the reproducer so that it's reproducible on the command line I could look into it but without this, it's pretty hard to investigate...

**Comment by martinbonnin** [comment] 2022-04-01 11:58
Turns out[ bumping the `minSdkVersion` to 24](https://github.com/martinbonnin/r8bug/commit/176186a08ee54c0f0c0ce28fee4c72fa8af74367) so that desugaring is always skipped makes the problem reproducible from the command line. Many thanks to @lwasyl for finding this 🤗 . I'll keep looking what the actual root cause is...

**Comment by martinbonnin** [comment] 2022-04-02 22:03
Turns out this is a known AGP issue. It'll be fixed in 7.1.3: https://issuetracker.google.com/issues/223365583

As for workarounds, I'm not really sure... You _could_ commit a bump in the Gradle version at the same time as you commit the `alwaysGenerateTypesMatching`. That'd technically force a non-incremental dex transform next time (plus keeps your Gradle version up to date 😄 ). Or revert to 7.0.x if that's a possibility.

**Comment by kenyee** [comment] 2022-04-03 01:26
Thanks for the dig Martin 🙂

**Closed** 2022-04-04 11:09 UTC

**Comment by theBradfo** [comment] 2022-04-04 13:29
Thanks Martin!  Now I guess we just need to wait for them to actually publish 7.1.3 😭, but at least we know the problem and that it should be addressed imminently!

**Comment by martinbonnin** [comment] 2022-04-07 22:00
[7.1.3 is out 🎉](https://twitter.com/AGPVersions/status/1512097954403868678?t=QSdR5wAkENYhMhv0PX2FzQ&s=19)
